export const emailStyles = {
    main: {
        backgroundColor: "#ffffff",
        fontFamily: "HelveticaNeue,Helvetica,Arial,sans-serif",
    },
    container: {
        backgroundColor: "#ffffff",
        border: "1px solid #eee",
        borderRadius: "5px",
        boxShadow: "0 5px 10px rgba(20,50,70,.2)",
        marginTop: "20px",
        maxWidth: "360px",
        margin: "0 auto",
        padding: "68px 0 130px",
    },
    logo: {
        margin: "0 auto",
        marginBottom: "24px",
    },
    tertiary: {
        color: "#0a85ea",
        fontSize: "11px",
        fontWeight: 700,
        fontFamily: "HelveticaNeue,Helvetica,Arial,sans-serif",
        height: "16px",
        letterSpacing: "0",
        lineHeight: "16px",
        margin: "16px 8px 8px 8px",
        textTransform: "uppercase" as const,
        textAlign: "center" as const,
    },
    secondary: {
        color: "#000",
        display: "inline-block",
        fontFamily: "HelveticaNeue-Medium,Helvetica,Arial,sans-serif",
        fontSize: "20px",
        fontWeight: 500,
        lineHeight: "24px",
        marginBottom: "0",
        marginTop: "0",
        width: "100%",
        textAlign: "center" as const,
    },
    heading: {
        color: "#000",
        display: "inline-block",
        fontFamily: "HelveticaNeue-Medium,Helvetica,Arial,sans-serif",
        fontSize: "20px",
        fontWeight: 500,
        lineHeight: "24px",
        marginBottom: "0",
        marginTop: "0",
        padding: "0 20px",
        width: "calc(100% - 40px)",
        textAlign: "center" as const,
    },
    codeContainer: {
        background: "rgba(0,0,0,.05)",
        borderRadius: "4px",
        margin: "16px auto 14px",
        verticalAlign: "middle",
        width: "280px",
    },
    code: {
        color: "#000",
        fontFamily: "HelveticaNeue-Bold",
        fontSize: "32px",
        fontWeight: 700,
        letterSpacing: "6px",
        lineHeight: "40px",
        paddingBottom: "8px",
        paddingTop: "8px",
        margin: "0 auto",
        display: "block",
        textAlign: "center" as const,
    },
    paragraph: {
        color: "#444",
        fontSize: "15px",
        fontFamily: "HelveticaNeue,Helvetica,Arial,sans-serif",
        letterSpacing: "0",
        lineHeight: "23px",
        padding: "0 40px",
        margin: "0",
        marginTop: "10px",
        textAlign: "center" as const,
    },
    footer: {
        color: "#000",
        fontSize: "12px",
        fontWeight: 800,
        letterSpacing: "0",
        lineHeight: "23px",
        margin: "0",
        marginTop: "20px",
        fontFamily: "HelveticaNeue,Helvetica,Arial,sans-serif",
        textAlign: "center" as const,
        textTransform: "uppercase" as const,
    },
    button: {
        backgroundColor: "#007ee6",
        borderRadius: "4px",
        color: "#fff",
        fontFamily: "'Open Sans', 'Helvetica Neue', Arial",
        fontSize: "15px",
        textDecoration: "none",
        textAlign: "center" as const,
        display: "block",
        width: "210px",
        margin: "20px auto 0",
        padding: "14px 7px",
    },
    positionContainer: {
        background: "rgba(0,0,0,.05)",
        borderRadius: "4px",
        margin: "16px auto 14px",
        verticalAlign: "middle",
        width: "280px",
        padding: "16px 0",
    },
    positionLabel: {
        color: "#666",
        fontFamily: "HelveticaNeue,Helvetica,Arial,sans-serif",
        fontSize: "14px",
        fontWeight: 400,
        margin: "0",
        textAlign: "center" as const,
        display: "block",
    },
    positionNumber: {
        color: "#000",
        fontFamily: "HelveticaNeue-Bold",
        fontSize: "48px",
        fontWeight: 700,
        lineHeight: "56px",
        margin: "8px 0 0 0",
        display: "block",
        textAlign: "center" as const,
    },
};
