import { assert, describe, test } from "vitest";
import { parseValidStudyPrograms } from "~/lib/auth/feide";

describe("feide parse valid study programs", () => {
    test("parses valid study programs", () => {
        const groups = [
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2501:1",
                type: "fc:fs:emne",
                displayName: "Fordypningsprosjekt",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:klasse:ntnu.no:BIDATA:2023H:OT",
                type: "fc:fs:klasse",
                displayName:
                    "Klasse Data - bachelor i ingeniørfag OT Høst 2023",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:fs:fs:kull:ntnu.no:BIDATA:2023H",
            },
            {
                id: "fc:fs:fs:prg:ntnu.no:BIDATA",
                type: "fc:fs:prg",
                displayName: "Data - bachelor i ingeniørfag",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:org:ntnu.no",
                url: "https://www.ntnu.no/studier/bidata",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2003:1",
                type: "fc:fs:emne",
                displayName: "Programmering 2",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2002:1",
                type: "fc:fs:emne",
                displayName: "Databaser",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:HMS0002:1",
                type: "fc:fs:emne",
                displayName: "HMS-kurs for 1. årsstudenter",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2023-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:EXPH0600:1",
                type: "fc:fs:emne",
                displayName: "Examen philosophicum for ingeniørfag ",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:INGT1002:1",
                type: "fc:fs:emne",
                displayName: "Programmering, numerikk og sikkerhet",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2023-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IMAT3011:1",
                type: "fc:fs:emne",
                displayName: "Matematikk for ingeniørfag 3 A",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT1005:1",
                type: "fc:fs:emne",
                displayName: "Systemutvikling",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT1003:1",
                type: "fc:fs:emne",
                displayName: "Programmering 1",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2023-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IMAT1002:1",
                type: "fc:fs:emne",
                displayName: "Matematikk for ingeniørfag 1",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2023-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT1004:1",
                type: "fc:fs:emne",
                displayName: "Teambasert samhandling",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2023-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:str:ntnu.no:BIDATA-SYSUTV",
                type: "fc:fs:str",
                displayName: "Systemutvikling",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2202:1",
                type: "fc:fs:emne",
                displayName: "Operativsystemer",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IMAT2024:1",
                type: "fc:fs:emne",
                displayName: "Matematikk for ingeniørfag 2 D",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:kull:ntnu.no:BIDATA:2023H",
                type: "fc:fs:kull",
                displayName: "Kull for Høst 2023 Data - bachelor i ingeniørfag",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:fs:fs:prg:BIDATA",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2901:1",
                type: "fc:fs:emne",
                displayName: "Bacheloroppgave",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2025-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:ISTT1003:1",
                type: "fc:fs:emne",
                displayName: "Statistikk",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2104:1",
                type: "fc:fs:emne",
                displayName: "Nettverksprogrammering",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2025-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IFYT1002:1",
                type: "fc:fs:emne",
                displayName: "Fysikk",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2025-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2106:1",
                type: "fc:fs:emne",
                displayName: "Systemutvikling 2 med smidig prosjekt",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2025-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2105:1",
                type: "fc:fs:emne",
                displayName: "Full-stack applikasjonsutvikling",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2025-08-14T22:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2503:1",
                type: "fc:fs:emne",
                displayName: "Sikkerhet i programvare og kryptografi",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2506:1",
                type: "fc:fs:emne",
                displayName: "Applikasjonsutvikling for mobile enheter",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                },
                parent: "fc:org:ntnu.no",
            },
            {
                id: "fc:fs:fs:emne:ntnu.no:IDATT2101:1",
                type: "fc:fs:emne",
                displayName: "Algoritmer og datastrukturer",
                membership: {
                    basic: "member",
                    active: true,
                    displayName: "Student",
                    fsroles: ["STUDENT"],
                    notAfter: "2024-12-14T23:00:00Z",
                    subjectRelations: "undervisning",
                },
                parent: "fc:org:ntnu.no",
            },
        ];

        const validStudyPrograms = parseValidStudyPrograms(groups);
        assert.equal(validStudyPrograms.length, 1);
        assert.equal(validStudyPrograms[0]?.code, "BIDATA");
        assert.equal(validStudyPrograms[0]?.startYear, 2023);
    });
});
