/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InteresseRouteImport } from './routes/interesse'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainToddelRouteImport } from './routes/_main/toddel'
import { Route as MainTilbakemeldingRouteImport } from './routes/_main/tilbakemelding'
import { Route as MainNyStudentRouteImport } from './routes/_main/ny-student'
import { Route as MainLoggInnRouteImport } from './routes/_main/logg-inn'
import { Route as MainEndringsloggRouteImport } from './routes/_main/endringslogg'
import { Route as MainBedrifterRouteImport } from './routes/_main/bedrifter'
import { Route as MainAdminRouteImport } from './routes/_main/admin'
import { Route as MainStillingsannonserIndexRouteImport } from './routes/_main/stillingsannonser/index'
import { Route as MainNyheterIndexRouteImport } from './routes/_main/nyheter/index'
import { Route as MainGrupperIndexRouteImport } from './routes/_main/grupper/index'
import { Route as MainArrangementerIndexRouteImport } from './routes/_main/arrangementer/index'
import { Route as MainAdminIndexRouteImport } from './routes/_main/admin/index'
import { Route as MainStillingsannonserIdRouteImport } from './routes/_main/stillingsannonser/$id'
import { Route as MainSporreskjemaIdRouteImport } from './routes/_main/sporreskjema/$id'
import { Route as MainProfilUserIdRouteImport } from './routes/_main/profil/$userId'
import { Route as MainNyheterIdRouteImport } from './routes/_main/nyheter/$id'
import { Route as MainGrupperSlugRouteImport } from './routes/_main/grupper/$slug'
import { Route as MainArrangementerIdRouteImport } from './routes/_main/arrangementer/$id'
import { Route as MainAdminStillingsannonserIndexRouteImport } from './routes/_main/admin/stillingsannonser/index'
import { Route as MainAdminSkjemaerIndexRouteImport } from './routes/_main/admin/skjemaer/index'
import { Route as MainAdminNyheterIndexRouteImport } from './routes/_main/admin/nyheter/index'
import { Route as MainAdminArrangementerIndexRouteImport } from './routes/_main/admin/arrangementer/index'
import { Route as MainAdminStillingsannonserNyRouteImport } from './routes/_main/admin/stillingsannonser/ny'
import { Route as MainAdminStillingsannonserJobPostIdRouteImport } from './routes/_main/admin/stillingsannonser/$jobPostId'
import { Route as MainAdminSkjemaerNyRouteImport } from './routes/_main/admin/skjemaer/ny'
import { Route as MainAdminSkjemaerFormIdRouteImport } from './routes/_main/admin/skjemaer/$formId'
import { Route as MainAdminNyheterNyRouteImport } from './routes/_main/admin/nyheter/ny'
import { Route as MainAdminNyheterNewsIdRouteImport } from './routes/_main/admin/nyheter/$newsId'
import { Route as MainAdminArrangementerNyRouteImport } from './routes/_main/admin/arrangementer/ny'
import { Route as MainAdminArrangementerEventIdRouteImport } from './routes/_main/admin/arrangementer/$eventId'

const InteresseRoute = InteresseRouteImport.update({
  id: '/interesse',
  path: '/interesse',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainToddelRoute = MainToddelRouteImport.update({
  id: '/toddel',
  path: '/toddel',
  getParentRoute: () => MainRoute,
} as any)
const MainTilbakemeldingRoute = MainTilbakemeldingRouteImport.update({
  id: '/tilbakemelding',
  path: '/tilbakemelding',
  getParentRoute: () => MainRoute,
} as any)
const MainNyStudentRoute = MainNyStudentRouteImport.update({
  id: '/ny-student',
  path: '/ny-student',
  getParentRoute: () => MainRoute,
} as any)
const MainLoggInnRoute = MainLoggInnRouteImport.update({
  id: '/logg-inn',
  path: '/logg-inn',
  getParentRoute: () => MainRoute,
} as any)
const MainEndringsloggRoute = MainEndringsloggRouteImport.update({
  id: '/endringslogg',
  path: '/endringslogg',
  getParentRoute: () => MainRoute,
} as any)
const MainBedrifterRoute = MainBedrifterRouteImport.update({
  id: '/bedrifter',
  path: '/bedrifter',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminRoute = MainAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => MainRoute,
} as any)
const MainStillingsannonserIndexRoute =
  MainStillingsannonserIndexRouteImport.update({
    id: '/stillingsannonser/',
    path: '/stillingsannonser/',
    getParentRoute: () => MainRoute,
  } as any)
const MainNyheterIndexRoute = MainNyheterIndexRouteImport.update({
  id: '/nyheter/',
  path: '/nyheter/',
  getParentRoute: () => MainRoute,
} as any)
const MainGrupperIndexRoute = MainGrupperIndexRouteImport.update({
  id: '/grupper/',
  path: '/grupper/',
  getParentRoute: () => MainRoute,
} as any)
const MainArrangementerIndexRoute = MainArrangementerIndexRouteImport.update({
  id: '/arrangementer/',
  path: '/arrangementer/',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminIndexRoute = MainAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainStillingsannonserIdRoute = MainStillingsannonserIdRouteImport.update({
  id: '/stillingsannonser/$id',
  path: '/stillingsannonser/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainSporreskjemaIdRoute = MainSporreskjemaIdRouteImport.update({
  id: '/sporreskjema/$id',
  path: '/sporreskjema/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainProfilUserIdRoute = MainProfilUserIdRouteImport.update({
  id: '/profil/$userId',
  path: '/profil/$userId',
  getParentRoute: () => MainRoute,
} as any)
const MainNyheterIdRoute = MainNyheterIdRouteImport.update({
  id: '/nyheter/$id',
  path: '/nyheter/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainGrupperSlugRoute = MainGrupperSlugRouteImport.update({
  id: '/grupper/$slug',
  path: '/grupper/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainArrangementerIdRoute = MainArrangementerIdRouteImport.update({
  id: '/arrangementer/$id',
  path: '/arrangementer/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainAdminStillingsannonserIndexRoute =
  MainAdminStillingsannonserIndexRouteImport.update({
    id: '/stillingsannonser/',
    path: '/stillingsannonser/',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminSkjemaerIndexRoute = MainAdminSkjemaerIndexRouteImport.update({
  id: '/skjemaer/',
  path: '/skjemaer/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminNyheterIndexRoute = MainAdminNyheterIndexRouteImport.update({
  id: '/nyheter/',
  path: '/nyheter/',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminArrangementerIndexRoute =
  MainAdminArrangementerIndexRouteImport.update({
    id: '/arrangementer/',
    path: '/arrangementer/',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminStillingsannonserNyRoute =
  MainAdminStillingsannonserNyRouteImport.update({
    id: '/stillingsannonser/ny',
    path: '/stillingsannonser/ny',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminStillingsannonserJobPostIdRoute =
  MainAdminStillingsannonserJobPostIdRouteImport.update({
    id: '/stillingsannonser/$jobPostId',
    path: '/stillingsannonser/$jobPostId',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminSkjemaerNyRoute = MainAdminSkjemaerNyRouteImport.update({
  id: '/skjemaer/ny',
  path: '/skjemaer/ny',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminSkjemaerFormIdRoute = MainAdminSkjemaerFormIdRouteImport.update({
  id: '/skjemaer/$formId',
  path: '/skjemaer/$formId',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminNyheterNyRoute = MainAdminNyheterNyRouteImport.update({
  id: '/nyheter/ny',
  path: '/nyheter/ny',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminNyheterNewsIdRoute = MainAdminNyheterNewsIdRouteImport.update({
  id: '/nyheter/$newsId',
  path: '/nyheter/$newsId',
  getParentRoute: () => MainAdminRoute,
} as any)
const MainAdminArrangementerNyRoute =
  MainAdminArrangementerNyRouteImport.update({
    id: '/arrangementer/ny',
    path: '/arrangementer/ny',
    getParentRoute: () => MainAdminRoute,
  } as any)
const MainAdminArrangementerEventIdRoute =
  MainAdminArrangementerEventIdRouteImport.update({
    id: '/arrangementer/$eventId',
    path: '/arrangementer/$eventId',
    getParentRoute: () => MainAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/interesse': typeof InteresseRoute
  '/admin': typeof MainAdminRouteWithChildren
  '/bedrifter': typeof MainBedrifterRoute
  '/endringslogg': typeof MainEndringsloggRoute
  '/logg-inn': typeof MainLoggInnRoute
  '/ny-student': typeof MainNyStudentRoute
  '/tilbakemelding': typeof MainTilbakemeldingRoute
  '/toddel': typeof MainToddelRoute
  '/arrangementer/$id': typeof MainArrangementerIdRoute
  '/grupper/$slug': typeof MainGrupperSlugRoute
  '/nyheter/$id': typeof MainNyheterIdRoute
  '/profil/$userId': typeof MainProfilUserIdRoute
  '/sporreskjema/$id': typeof MainSporreskjemaIdRoute
  '/stillingsannonser/$id': typeof MainStillingsannonserIdRoute
  '/admin/': typeof MainAdminIndexRoute
  '/arrangementer/': typeof MainArrangementerIndexRoute
  '/grupper/': typeof MainGrupperIndexRoute
  '/nyheter/': typeof MainNyheterIndexRoute
  '/stillingsannonser/': typeof MainStillingsannonserIndexRoute
  '/admin/arrangementer/$eventId': typeof MainAdminArrangementerEventIdRoute
  '/admin/arrangementer/ny': typeof MainAdminArrangementerNyRoute
  '/admin/nyheter/$newsId': typeof MainAdminNyheterNewsIdRoute
  '/admin/nyheter/ny': typeof MainAdminNyheterNyRoute
  '/admin/skjemaer/$formId': typeof MainAdminSkjemaerFormIdRoute
  '/admin/skjemaer/ny': typeof MainAdminSkjemaerNyRoute
  '/admin/stillingsannonser/$jobPostId': typeof MainAdminStillingsannonserJobPostIdRoute
  '/admin/stillingsannonser/ny': typeof MainAdminStillingsannonserNyRoute
  '/admin/arrangementer/': typeof MainAdminArrangementerIndexRoute
  '/admin/nyheter/': typeof MainAdminNyheterIndexRoute
  '/admin/skjemaer/': typeof MainAdminSkjemaerIndexRoute
  '/admin/stillingsannonser/': typeof MainAdminStillingsannonserIndexRoute
}
export interface FileRoutesByTo {
  '/interesse': typeof InteresseRoute
  '/bedrifter': typeof MainBedrifterRoute
  '/endringslogg': typeof MainEndringsloggRoute
  '/logg-inn': typeof MainLoggInnRoute
  '/ny-student': typeof MainNyStudentRoute
  '/tilbakemelding': typeof MainTilbakemeldingRoute
  '/toddel': typeof MainToddelRoute
  '/': typeof MainIndexRoute
  '/arrangementer/$id': typeof MainArrangementerIdRoute
  '/grupper/$slug': typeof MainGrupperSlugRoute
  '/nyheter/$id': typeof MainNyheterIdRoute
  '/profil/$userId': typeof MainProfilUserIdRoute
  '/sporreskjema/$id': typeof MainSporreskjemaIdRoute
  '/stillingsannonser/$id': typeof MainStillingsannonserIdRoute
  '/admin': typeof MainAdminIndexRoute
  '/arrangementer': typeof MainArrangementerIndexRoute
  '/grupper': typeof MainGrupperIndexRoute
  '/nyheter': typeof MainNyheterIndexRoute
  '/stillingsannonser': typeof MainStillingsannonserIndexRoute
  '/admin/arrangementer/$eventId': typeof MainAdminArrangementerEventIdRoute
  '/admin/arrangementer/ny': typeof MainAdminArrangementerNyRoute
  '/admin/nyheter/$newsId': typeof MainAdminNyheterNewsIdRoute
  '/admin/nyheter/ny': typeof MainAdminNyheterNyRoute
  '/admin/skjemaer/$formId': typeof MainAdminSkjemaerFormIdRoute
  '/admin/skjemaer/ny': typeof MainAdminSkjemaerNyRoute
  '/admin/stillingsannonser/$jobPostId': typeof MainAdminStillingsannonserJobPostIdRoute
  '/admin/stillingsannonser/ny': typeof MainAdminStillingsannonserNyRoute
  '/admin/arrangementer': typeof MainAdminArrangementerIndexRoute
  '/admin/nyheter': typeof MainAdminNyheterIndexRoute
  '/admin/skjemaer': typeof MainAdminSkjemaerIndexRoute
  '/admin/stillingsannonser': typeof MainAdminStillingsannonserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/interesse': typeof InteresseRoute
  '/_main/admin': typeof MainAdminRouteWithChildren
  '/_main/bedrifter': typeof MainBedrifterRoute
  '/_main/endringslogg': typeof MainEndringsloggRoute
  '/_main/logg-inn': typeof MainLoggInnRoute
  '/_main/ny-student': typeof MainNyStudentRoute
  '/_main/tilbakemelding': typeof MainTilbakemeldingRoute
  '/_main/toddel': typeof MainToddelRoute
  '/_main/': typeof MainIndexRoute
  '/_main/arrangementer/$id': typeof MainArrangementerIdRoute
  '/_main/grupper/$slug': typeof MainGrupperSlugRoute
  '/_main/nyheter/$id': typeof MainNyheterIdRoute
  '/_main/profil/$userId': typeof MainProfilUserIdRoute
  '/_main/sporreskjema/$id': typeof MainSporreskjemaIdRoute
  '/_main/stillingsannonser/$id': typeof MainStillingsannonserIdRoute
  '/_main/admin/': typeof MainAdminIndexRoute
  '/_main/arrangementer/': typeof MainArrangementerIndexRoute
  '/_main/grupper/': typeof MainGrupperIndexRoute
  '/_main/nyheter/': typeof MainNyheterIndexRoute
  '/_main/stillingsannonser/': typeof MainStillingsannonserIndexRoute
  '/_main/admin/arrangementer/$eventId': typeof MainAdminArrangementerEventIdRoute
  '/_main/admin/arrangementer/ny': typeof MainAdminArrangementerNyRoute
  '/_main/admin/nyheter/$newsId': typeof MainAdminNyheterNewsIdRoute
  '/_main/admin/nyheter/ny': typeof MainAdminNyheterNyRoute
  '/_main/admin/skjemaer/$formId': typeof MainAdminSkjemaerFormIdRoute
  '/_main/admin/skjemaer/ny': typeof MainAdminSkjemaerNyRoute
  '/_main/admin/stillingsannonser/$jobPostId': typeof MainAdminStillingsannonserJobPostIdRoute
  '/_main/admin/stillingsannonser/ny': typeof MainAdminStillingsannonserNyRoute
  '/_main/admin/arrangementer/': typeof MainAdminArrangementerIndexRoute
  '/_main/admin/nyheter/': typeof MainAdminNyheterIndexRoute
  '/_main/admin/skjemaer/': typeof MainAdminSkjemaerIndexRoute
  '/_main/admin/stillingsannonser/': typeof MainAdminStillingsannonserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interesse'
    | '/admin'
    | '/bedrifter'
    | '/endringslogg'
    | '/logg-inn'
    | '/ny-student'
    | '/tilbakemelding'
    | '/toddel'
    | '/arrangementer/$id'
    | '/grupper/$slug'
    | '/nyheter/$id'
    | '/profil/$userId'
    | '/sporreskjema/$id'
    | '/stillingsannonser/$id'
    | '/admin/'
    | '/arrangementer/'
    | '/grupper/'
    | '/nyheter/'
    | '/stillingsannonser/'
    | '/admin/arrangementer/$eventId'
    | '/admin/arrangementer/ny'
    | '/admin/nyheter/$newsId'
    | '/admin/nyheter/ny'
    | '/admin/skjemaer/$formId'
    | '/admin/skjemaer/ny'
    | '/admin/stillingsannonser/$jobPostId'
    | '/admin/stillingsannonser/ny'
    | '/admin/arrangementer/'
    | '/admin/nyheter/'
    | '/admin/skjemaer/'
    | '/admin/stillingsannonser/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/interesse'
    | '/bedrifter'
    | '/endringslogg'
    | '/logg-inn'
    | '/ny-student'
    | '/tilbakemelding'
    | '/toddel'
    | '/'
    | '/arrangementer/$id'
    | '/grupper/$slug'
    | '/nyheter/$id'
    | '/profil/$userId'
    | '/sporreskjema/$id'
    | '/stillingsannonser/$id'
    | '/admin'
    | '/arrangementer'
    | '/grupper'
    | '/nyheter'
    | '/stillingsannonser'
    | '/admin/arrangementer/$eventId'
    | '/admin/arrangementer/ny'
    | '/admin/nyheter/$newsId'
    | '/admin/nyheter/ny'
    | '/admin/skjemaer/$formId'
    | '/admin/skjemaer/ny'
    | '/admin/stillingsannonser/$jobPostId'
    | '/admin/stillingsannonser/ny'
    | '/admin/arrangementer'
    | '/admin/nyheter'
    | '/admin/skjemaer'
    | '/admin/stillingsannonser'
  id:
    | '__root__'
    | '/_main'
    | '/interesse'
    | '/_main/admin'
    | '/_main/bedrifter'
    | '/_main/endringslogg'
    | '/_main/logg-inn'
    | '/_main/ny-student'
    | '/_main/tilbakemelding'
    | '/_main/toddel'
    | '/_main/'
    | '/_main/arrangementer/$id'
    | '/_main/grupper/$slug'
    | '/_main/nyheter/$id'
    | '/_main/profil/$userId'
    | '/_main/sporreskjema/$id'
    | '/_main/stillingsannonser/$id'
    | '/_main/admin/'
    | '/_main/arrangementer/'
    | '/_main/grupper/'
    | '/_main/nyheter/'
    | '/_main/stillingsannonser/'
    | '/_main/admin/arrangementer/$eventId'
    | '/_main/admin/arrangementer/ny'
    | '/_main/admin/nyheter/$newsId'
    | '/_main/admin/nyheter/ny'
    | '/_main/admin/skjemaer/$formId'
    | '/_main/admin/skjemaer/ny'
    | '/_main/admin/stillingsannonser/$jobPostId'
    | '/_main/admin/stillingsannonser/ny'
    | '/_main/admin/arrangementer/'
    | '/_main/admin/nyheter/'
    | '/_main/admin/skjemaer/'
    | '/_main/admin/stillingsannonser/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  InteresseRoute: typeof InteresseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/interesse': {
      id: '/interesse'
      path: '/interesse'
      fullPath: '/interesse'
      preLoaderRoute: typeof InteresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/toddel': {
      id: '/_main/toddel'
      path: '/toddel'
      fullPath: '/toddel'
      preLoaderRoute: typeof MainToddelRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/tilbakemelding': {
      id: '/_main/tilbakemelding'
      path: '/tilbakemelding'
      fullPath: '/tilbakemelding'
      preLoaderRoute: typeof MainTilbakemeldingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ny-student': {
      id: '/_main/ny-student'
      path: '/ny-student'
      fullPath: '/ny-student'
      preLoaderRoute: typeof MainNyStudentRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/logg-inn': {
      id: '/_main/logg-inn'
      path: '/logg-inn'
      fullPath: '/logg-inn'
      preLoaderRoute: typeof MainLoggInnRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/endringslogg': {
      id: '/_main/endringslogg'
      path: '/endringslogg'
      fullPath: '/endringslogg'
      preLoaderRoute: typeof MainEndringsloggRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bedrifter': {
      id: '/_main/bedrifter'
      path: '/bedrifter'
      fullPath: '/bedrifter'
      preLoaderRoute: typeof MainBedrifterRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin': {
      id: '/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof MainAdminRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/stillingsannonser/': {
      id: '/_main/stillingsannonser/'
      path: '/stillingsannonser'
      fullPath: '/stillingsannonser/'
      preLoaderRoute: typeof MainStillingsannonserIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/nyheter/': {
      id: '/_main/nyheter/'
      path: '/nyheter'
      fullPath: '/nyheter/'
      preLoaderRoute: typeof MainNyheterIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/grupper/': {
      id: '/_main/grupper/'
      path: '/grupper'
      fullPath: '/grupper/'
      preLoaderRoute: typeof MainGrupperIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/arrangementer/': {
      id: '/_main/arrangementer/'
      path: '/arrangementer'
      fullPath: '/arrangementer/'
      preLoaderRoute: typeof MainArrangementerIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/': {
      id: '/_main/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof MainAdminIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/stillingsannonser/$id': {
      id: '/_main/stillingsannonser/$id'
      path: '/stillingsannonser/$id'
      fullPath: '/stillingsannonser/$id'
      preLoaderRoute: typeof MainStillingsannonserIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sporreskjema/$id': {
      id: '/_main/sporreskjema/$id'
      path: '/sporreskjema/$id'
      fullPath: '/sporreskjema/$id'
      preLoaderRoute: typeof MainSporreskjemaIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profil/$userId': {
      id: '/_main/profil/$userId'
      path: '/profil/$userId'
      fullPath: '/profil/$userId'
      preLoaderRoute: typeof MainProfilUserIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/nyheter/$id': {
      id: '/_main/nyheter/$id'
      path: '/nyheter/$id'
      fullPath: '/nyheter/$id'
      preLoaderRoute: typeof MainNyheterIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/grupper/$slug': {
      id: '/_main/grupper/$slug'
      path: '/grupper/$slug'
      fullPath: '/grupper/$slug'
      preLoaderRoute: typeof MainGrupperSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/arrangementer/$id': {
      id: '/_main/arrangementer/$id'
      path: '/arrangementer/$id'
      fullPath: '/arrangementer/$id'
      preLoaderRoute: typeof MainArrangementerIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/admin/stillingsannonser/': {
      id: '/_main/admin/stillingsannonser/'
      path: '/stillingsannonser'
      fullPath: '/admin/stillingsannonser/'
      preLoaderRoute: typeof MainAdminStillingsannonserIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/skjemaer/': {
      id: '/_main/admin/skjemaer/'
      path: '/skjemaer'
      fullPath: '/admin/skjemaer/'
      preLoaderRoute: typeof MainAdminSkjemaerIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/nyheter/': {
      id: '/_main/admin/nyheter/'
      path: '/nyheter'
      fullPath: '/admin/nyheter/'
      preLoaderRoute: typeof MainAdminNyheterIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/arrangementer/': {
      id: '/_main/admin/arrangementer/'
      path: '/arrangementer'
      fullPath: '/admin/arrangementer/'
      preLoaderRoute: typeof MainAdminArrangementerIndexRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/stillingsannonser/ny': {
      id: '/_main/admin/stillingsannonser/ny'
      path: '/stillingsannonser/ny'
      fullPath: '/admin/stillingsannonser/ny'
      preLoaderRoute: typeof MainAdminStillingsannonserNyRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/stillingsannonser/$jobPostId': {
      id: '/_main/admin/stillingsannonser/$jobPostId'
      path: '/stillingsannonser/$jobPostId'
      fullPath: '/admin/stillingsannonser/$jobPostId'
      preLoaderRoute: typeof MainAdminStillingsannonserJobPostIdRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/skjemaer/ny': {
      id: '/_main/admin/skjemaer/ny'
      path: '/skjemaer/ny'
      fullPath: '/admin/skjemaer/ny'
      preLoaderRoute: typeof MainAdminSkjemaerNyRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/skjemaer/$formId': {
      id: '/_main/admin/skjemaer/$formId'
      path: '/skjemaer/$formId'
      fullPath: '/admin/skjemaer/$formId'
      preLoaderRoute: typeof MainAdminSkjemaerFormIdRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/nyheter/ny': {
      id: '/_main/admin/nyheter/ny'
      path: '/nyheter/ny'
      fullPath: '/admin/nyheter/ny'
      preLoaderRoute: typeof MainAdminNyheterNyRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/nyheter/$newsId': {
      id: '/_main/admin/nyheter/$newsId'
      path: '/nyheter/$newsId'
      fullPath: '/admin/nyheter/$newsId'
      preLoaderRoute: typeof MainAdminNyheterNewsIdRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/arrangementer/ny': {
      id: '/_main/admin/arrangementer/ny'
      path: '/arrangementer/ny'
      fullPath: '/admin/arrangementer/ny'
      preLoaderRoute: typeof MainAdminArrangementerNyRouteImport
      parentRoute: typeof MainAdminRoute
    }
    '/_main/admin/arrangementer/$eventId': {
      id: '/_main/admin/arrangementer/$eventId'
      path: '/arrangementer/$eventId'
      fullPath: '/admin/arrangementer/$eventId'
      preLoaderRoute: typeof MainAdminArrangementerEventIdRouteImport
      parentRoute: typeof MainAdminRoute
    }
  }
}

interface MainAdminRouteChildren {
  MainAdminIndexRoute: typeof MainAdminIndexRoute
  MainAdminArrangementerEventIdRoute: typeof MainAdminArrangementerEventIdRoute
  MainAdminArrangementerNyRoute: typeof MainAdminArrangementerNyRoute
  MainAdminNyheterNewsIdRoute: typeof MainAdminNyheterNewsIdRoute
  MainAdminNyheterNyRoute: typeof MainAdminNyheterNyRoute
  MainAdminSkjemaerFormIdRoute: typeof MainAdminSkjemaerFormIdRoute
  MainAdminSkjemaerNyRoute: typeof MainAdminSkjemaerNyRoute
  MainAdminStillingsannonserJobPostIdRoute: typeof MainAdminStillingsannonserJobPostIdRoute
  MainAdminStillingsannonserNyRoute: typeof MainAdminStillingsannonserNyRoute
  MainAdminArrangementerIndexRoute: typeof MainAdminArrangementerIndexRoute
  MainAdminNyheterIndexRoute: typeof MainAdminNyheterIndexRoute
  MainAdminSkjemaerIndexRoute: typeof MainAdminSkjemaerIndexRoute
  MainAdminStillingsannonserIndexRoute: typeof MainAdminStillingsannonserIndexRoute
}

const MainAdminRouteChildren: MainAdminRouteChildren = {
  MainAdminIndexRoute: MainAdminIndexRoute,
  MainAdminArrangementerEventIdRoute: MainAdminArrangementerEventIdRoute,
  MainAdminArrangementerNyRoute: MainAdminArrangementerNyRoute,
  MainAdminNyheterNewsIdRoute: MainAdminNyheterNewsIdRoute,
  MainAdminNyheterNyRoute: MainAdminNyheterNyRoute,
  MainAdminSkjemaerFormIdRoute: MainAdminSkjemaerFormIdRoute,
  MainAdminSkjemaerNyRoute: MainAdminSkjemaerNyRoute,
  MainAdminStillingsannonserJobPostIdRoute:
    MainAdminStillingsannonserJobPostIdRoute,
  MainAdminStillingsannonserNyRoute: MainAdminStillingsannonserNyRoute,
  MainAdminArrangementerIndexRoute: MainAdminArrangementerIndexRoute,
  MainAdminNyheterIndexRoute: MainAdminNyheterIndexRoute,
  MainAdminSkjemaerIndexRoute: MainAdminSkjemaerIndexRoute,
  MainAdminStillingsannonserIndexRoute: MainAdminStillingsannonserIndexRoute,
}

const MainAdminRouteWithChildren = MainAdminRoute._addFileChildren(
  MainAdminRouteChildren,
)

interface MainRouteChildren {
  MainAdminRoute: typeof MainAdminRouteWithChildren
  MainBedrifterRoute: typeof MainBedrifterRoute
  MainEndringsloggRoute: typeof MainEndringsloggRoute
  MainLoggInnRoute: typeof MainLoggInnRoute
  MainNyStudentRoute: typeof MainNyStudentRoute
  MainTilbakemeldingRoute: typeof MainTilbakemeldingRoute
  MainToddelRoute: typeof MainToddelRoute
  MainIndexRoute: typeof MainIndexRoute
  MainArrangementerIdRoute: typeof MainArrangementerIdRoute
  MainGrupperSlugRoute: typeof MainGrupperSlugRoute
  MainNyheterIdRoute: typeof MainNyheterIdRoute
  MainProfilUserIdRoute: typeof MainProfilUserIdRoute
  MainSporreskjemaIdRoute: typeof MainSporreskjemaIdRoute
  MainStillingsannonserIdRoute: typeof MainStillingsannonserIdRoute
  MainArrangementerIndexRoute: typeof MainArrangementerIndexRoute
  MainGrupperIndexRoute: typeof MainGrupperIndexRoute
  MainNyheterIndexRoute: typeof MainNyheterIndexRoute
  MainStillingsannonserIndexRoute: typeof MainStillingsannonserIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAdminRoute: MainAdminRouteWithChildren,
  MainBedrifterRoute: MainBedrifterRoute,
  MainEndringsloggRoute: MainEndringsloggRoute,
  MainLoggInnRoute: MainLoggInnRoute,
  MainNyStudentRoute: MainNyStudentRoute,
  MainTilbakemeldingRoute: MainTilbakemeldingRoute,
  MainToddelRoute: MainToddelRoute,
  MainIndexRoute: MainIndexRoute,
  MainArrangementerIdRoute: MainArrangementerIdRoute,
  MainGrupperSlugRoute: MainGrupperSlugRoute,
  MainNyheterIdRoute: MainNyheterIdRoute,
  MainProfilUserIdRoute: MainProfilUserIdRoute,
  MainSporreskjemaIdRoute: MainSporreskjemaIdRoute,
  MainStillingsannonserIdRoute: MainStillingsannonserIdRoute,
  MainArrangementerIndexRoute: MainArrangementerIndexRoute,
  MainGrupperIndexRoute: MainGrupperIndexRoute,
  MainNyheterIndexRoute: MainNyheterIndexRoute,
  MainStillingsannonserIndexRoute: MainStillingsannonserIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  InteresseRoute: InteresseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
