
name: "photon_dev"

services:
  photon_db:
    image: postgres
    container_name: photon_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: photon_db
    ports:
      - "5432:5432"
    volumes:
      - photon_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d photon_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  photon_db_data: