/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AdminPrikkerRouteImport } from './routes/admin/prikker'
import { Route as AdminOpptakRouteImport } from './routes/admin/opptak'
import { Route as AdminNyheterRouteImport } from './routes/admin/nyheter'
import { Route as AdminGrupperRouteImport } from './routes/admin/grupper'
import { Route as AdminBrukereRouteImport } from './routes/admin/brukere'
import { Route as AdminBannereRouteImport } from './routes/admin/bannere'
import { Route as AdminArrangementerRouteImport } from './routes/admin/arrangementer'
import { Route as AdminAnnonserRouteImport } from './routes/admin/annonser'
import { Route as AdminSuperAdminRouteImport } from './routes/admin/_super-admin'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppToddelRouteImport } from './routes/_app/toddel'
import { Route as AppNyheterRouteImport } from './routes/_app/nyheter'
import { Route as AppKontraktRouteImport } from './routes/_app/kontrakt'
import { Route as AppKokebokRouteImport } from './routes/_app/kokebok'
import { Route as AppArrangementerRouteImport } from './routes/_app/arrangementer'
import { Route as AppAnnonserRouteImport } from './routes/_app/annonser'
import { Route as AppGrupperIndexRouteImport } from './routes/_app/grupper.index'
import { Route as AppGalleriIndexRouteImport } from './routes/_app/galleri.index'
import { Route as AdminSuperAdminLogsRouteImport } from './routes/admin/_super-admin/logs'
import { Route as AdminSuperAdminDatabaseRouteImport } from './routes/admin/_super-admin/database'
import { Route as AdminSuperAdminApiKeysRouteImport } from './routes/admin/_super-admin/api-keys'
import { Route as AppProfilMeRouteImport } from './routes/_app/profil.me'
import { Route as AppProfilIdRouteImport } from './routes/_app/profil/$id'
import { Route as AppPlaygroundMarkdownRouteImport } from './routes/_app/playground.markdown'
import { Route as AppGrupperSlugRouteImport } from './routes/_app/grupper.$slug'
import { Route as AppGalleriSlugRouteImport } from './routes/_app/galleri.$slug'
import { Route as AppProfilIdIndexRouteImport } from './routes/_app/profil/$id/index'
import { Route as AppProfilIdSporreskjemaerRouteImport } from './routes/_app/profil/$id/sporreskjemaer'
import { Route as AppProfilIdPrikkerRouteImport } from './routes/_app/profil/$id/prikker'
import { Route as AppProfilIdMedlemskapRouteImport } from './routes/_app/profil/$id/medlemskap'
import { Route as AppProfilIdArrangementerRouteImport } from './routes/_app/profil/$id/arrangementer'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminPrikkerRoute = AdminPrikkerRouteImport.update({
  id: '/prikker',
  path: '/prikker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpptakRoute = AdminOpptakRouteImport.update({
  id: '/opptak',
  path: '/opptak',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNyheterRoute = AdminNyheterRouteImport.update({
  id: '/nyheter',
  path: '/nyheter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrupperRoute = AdminGrupperRouteImport.update({
  id: '/grupper',
  path: '/grupper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrukereRoute = AdminBrukereRouteImport.update({
  id: '/brukere',
  path: '/brukere',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannereRoute = AdminBannereRouteImport.update({
  id: '/bannere',
  path: '/bannere',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArrangementerRoute = AdminArrangementerRouteImport.update({
  id: '/arrangementer',
  path: '/arrangementer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnonserRoute = AdminAnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuperAdminRoute = AdminSuperAdminRouteImport.update({
  id: '/_super-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppToddelRoute = AppToddelRouteImport.update({
  id: '/toddel',
  path: '/toddel',
  getParentRoute: () => AppRoute,
} as any)
const AppNyheterRoute = AppNyheterRouteImport.update({
  id: '/nyheter',
  path: '/nyheter',
  getParentRoute: () => AppRoute,
} as any)
const AppKontraktRoute = AppKontraktRouteImport.update({
  id: '/kontrakt',
  path: '/kontrakt',
  getParentRoute: () => AppRoute,
} as any)
const AppKokebokRoute = AppKokebokRouteImport.update({
  id: '/kokebok',
  path: '/kokebok',
  getParentRoute: () => AppRoute,
} as any)
const AppArrangementerRoute = AppArrangementerRouteImport.update({
  id: '/arrangementer',
  path: '/arrangementer',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnonserRoute = AppAnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => AppRoute,
} as any)
const AppGrupperIndexRoute = AppGrupperIndexRouteImport.update({
  id: '/grupper/',
  path: '/grupper/',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleriIndexRoute = AppGalleriIndexRouteImport.update({
  id: '/galleri/',
  path: '/galleri/',
  getParentRoute: () => AppRoute,
} as any)
const AdminSuperAdminLogsRoute = AdminSuperAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminSuperAdminRoute,
} as any)
const AdminSuperAdminDatabaseRoute = AdminSuperAdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminSuperAdminRoute,
} as any)
const AdminSuperAdminApiKeysRoute = AdminSuperAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminSuperAdminRoute,
} as any)
const AppProfilMeRoute = AppProfilMeRouteImport.update({
  id: '/profil/me',
  path: '/profil/me',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilIdRoute = AppProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundMarkdownRoute = AppPlaygroundMarkdownRouteImport.update({
  id: '/playground/markdown',
  path: '/playground/markdown',
  getParentRoute: () => AppRoute,
} as any)
const AppGrupperSlugRoute = AppGrupperSlugRouteImport.update({
  id: '/grupper/$slug',
  path: '/grupper/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleriSlugRoute = AppGalleriSlugRouteImport.update({
  id: '/galleri/$slug',
  path: '/galleri/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilIdIndexRoute = AppProfilIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfilIdRoute,
} as any)
const AppProfilIdSporreskjemaerRoute =
  AppProfilIdSporreskjemaerRouteImport.update({
    id: '/sporreskjemaer',
    path: '/sporreskjemaer',
    getParentRoute: () => AppProfilIdRoute,
  } as any)
const AppProfilIdPrikkerRoute = AppProfilIdPrikkerRouteImport.update({
  id: '/prikker',
  path: '/prikker',
  getParentRoute: () => AppProfilIdRoute,
} as any)
const AppProfilIdMedlemskapRoute = AppProfilIdMedlemskapRouteImport.update({
  id: '/medlemskap',
  path: '/medlemskap',
  getParentRoute: () => AppProfilIdRoute,
} as any)
const AppProfilIdArrangementerRoute =
  AppProfilIdArrangementerRouteImport.update({
    id: '/arrangementer',
    path: '/arrangementer',
    getParentRoute: () => AppProfilIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminSuperAdminRouteWithChildren
  '/annonser': typeof AppAnnonserRoute
  '/arrangementer': typeof AppArrangementerRoute
  '/kokebok': typeof AppKokebokRoute
  '/kontrakt': typeof AppKontraktRoute
  '/nyheter': typeof AppNyheterRoute
  '/toddel': typeof AppToddelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/annonser': typeof AdminAnnonserRoute
  '/admin/arrangementer': typeof AdminArrangementerRoute
  '/admin/bannere': typeof AdminBannereRoute
  '/admin/brukere': typeof AdminBrukereRoute
  '/admin/grupper': typeof AdminGrupperRoute
  '/admin/nyheter': typeof AdminNyheterRoute
  '/admin/opptak': typeof AdminOpptakRoute
  '/admin/prikker': typeof AdminPrikkerRoute
  '/admin/': typeof AdminIndexRoute
  '/galleri/$slug': typeof AppGalleriSlugRoute
  '/grupper/$slug': typeof AppGrupperSlugRoute
  '/playground/markdown': typeof AppPlaygroundMarkdownRoute
  '/profil/$id': typeof AppProfilIdRouteWithChildren
  '/profil/me': typeof AppProfilMeRoute
  '/admin/api-keys': typeof AdminSuperAdminApiKeysRoute
  '/admin/database': typeof AdminSuperAdminDatabaseRoute
  '/admin/logs': typeof AdminSuperAdminLogsRoute
  '/galleri/': typeof AppGalleriIndexRoute
  '/grupper/': typeof AppGrupperIndexRoute
  '/profil/$id/arrangementer': typeof AppProfilIdArrangementerRoute
  '/profil/$id/medlemskap': typeof AppProfilIdMedlemskapRoute
  '/profil/$id/prikker': typeof AppProfilIdPrikkerRoute
  '/profil/$id/sporreskjemaer': typeof AppProfilIdSporreskjemaerRoute
  '/profil/$id/': typeof AppProfilIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/annonser': typeof AppAnnonserRoute
  '/arrangementer': typeof AppArrangementerRoute
  '/kokebok': typeof AppKokebokRoute
  '/kontrakt': typeof AppKontraktRoute
  '/nyheter': typeof AppNyheterRoute
  '/toddel': typeof AppToddelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/admin/annonser': typeof AdminAnnonserRoute
  '/admin/arrangementer': typeof AdminArrangementerRoute
  '/admin/bannere': typeof AdminBannereRoute
  '/admin/brukere': typeof AdminBrukereRoute
  '/admin/grupper': typeof AdminGrupperRoute
  '/admin/nyheter': typeof AdminNyheterRoute
  '/admin/opptak': typeof AdminOpptakRoute
  '/admin/prikker': typeof AdminPrikkerRoute
  '/galleri/$slug': typeof AppGalleriSlugRoute
  '/grupper/$slug': typeof AppGrupperSlugRoute
  '/playground/markdown': typeof AppPlaygroundMarkdownRoute
  '/profil/me': typeof AppProfilMeRoute
  '/admin/api-keys': typeof AdminSuperAdminApiKeysRoute
  '/admin/database': typeof AdminSuperAdminDatabaseRoute
  '/admin/logs': typeof AdminSuperAdminLogsRoute
  '/galleri': typeof AppGalleriIndexRoute
  '/grupper': typeof AppGrupperIndexRoute
  '/profil/$id/arrangementer': typeof AppProfilIdArrangementerRoute
  '/profil/$id/medlemskap': typeof AppProfilIdMedlemskapRoute
  '/profil/$id/prikker': typeof AppProfilIdPrikkerRoute
  '/profil/$id/sporreskjemaer': typeof AppProfilIdSporreskjemaerRoute
  '/profil/$id': typeof AppProfilIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/annonser': typeof AppAnnonserRoute
  '/_app/arrangementer': typeof AppArrangementerRoute
  '/_app/kokebok': typeof AppKokebokRoute
  '/_app/kontrakt': typeof AppKontraktRoute
  '/_app/nyheter': typeof AppNyheterRoute
  '/_app/toddel': typeof AppToddelRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/admin/_super-admin': typeof AdminSuperAdminRouteWithChildren
  '/admin/annonser': typeof AdminAnnonserRoute
  '/admin/arrangementer': typeof AdminArrangementerRoute
  '/admin/bannere': typeof AdminBannereRoute
  '/admin/brukere': typeof AdminBrukereRoute
  '/admin/grupper': typeof AdminGrupperRoute
  '/admin/nyheter': typeof AdminNyheterRoute
  '/admin/opptak': typeof AdminOpptakRoute
  '/admin/prikker': typeof AdminPrikkerRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/galleri/$slug': typeof AppGalleriSlugRoute
  '/_app/grupper/$slug': typeof AppGrupperSlugRoute
  '/_app/playground/markdown': typeof AppPlaygroundMarkdownRoute
  '/_app/profil/$id': typeof AppProfilIdRouteWithChildren
  '/_app/profil/me': typeof AppProfilMeRoute
  '/admin/_super-admin/api-keys': typeof AdminSuperAdminApiKeysRoute
  '/admin/_super-admin/database': typeof AdminSuperAdminDatabaseRoute
  '/admin/_super-admin/logs': typeof AdminSuperAdminLogsRoute
  '/_app/galleri/': typeof AppGalleriIndexRoute
  '/_app/grupper/': typeof AppGrupperIndexRoute
  '/_app/profil/$id/arrangementer': typeof AppProfilIdArrangementerRoute
  '/_app/profil/$id/medlemskap': typeof AppProfilIdMedlemskapRoute
  '/_app/profil/$id/prikker': typeof AppProfilIdPrikkerRoute
  '/_app/profil/$id/sporreskjemaer': typeof AppProfilIdSporreskjemaerRoute
  '/_app/profil/$id/': typeof AppProfilIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/annonser'
    | '/arrangementer'
    | '/kokebok'
    | '/kontrakt'
    | '/nyheter'
    | '/toddel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/annonser'
    | '/admin/arrangementer'
    | '/admin/bannere'
    | '/admin/brukere'
    | '/admin/grupper'
    | '/admin/nyheter'
    | '/admin/opptak'
    | '/admin/prikker'
    | '/admin/'
    | '/galleri/$slug'
    | '/grupper/$slug'
    | '/playground/markdown'
    | '/profil/$id'
    | '/profil/me'
    | '/admin/api-keys'
    | '/admin/database'
    | '/admin/logs'
    | '/galleri/'
    | '/grupper/'
    | '/profil/$id/arrangementer'
    | '/profil/$id/medlemskap'
    | '/profil/$id/prikker'
    | '/profil/$id/sporreskjemaer'
    | '/profil/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annonser'
    | '/arrangementer'
    | '/kokebok'
    | '/kontrakt'
    | '/nyheter'
    | '/toddel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin'
    | '/admin/annonser'
    | '/admin/arrangementer'
    | '/admin/bannere'
    | '/admin/brukere'
    | '/admin/grupper'
    | '/admin/nyheter'
    | '/admin/opptak'
    | '/admin/prikker'
    | '/galleri/$slug'
    | '/grupper/$slug'
    | '/playground/markdown'
    | '/profil/me'
    | '/admin/api-keys'
    | '/admin/database'
    | '/admin/logs'
    | '/galleri'
    | '/grupper'
    | '/profil/$id/arrangementer'
    | '/profil/$id/medlemskap'
    | '/profil/$id/prikker'
    | '/profil/$id/sporreskjemaer'
    | '/profil/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/admin'
    | '/_app/annonser'
    | '/_app/arrangementer'
    | '/_app/kokebok'
    | '/_app/kontrakt'
    | '/_app/nyheter'
    | '/_app/toddel'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/admin/_super-admin'
    | '/admin/annonser'
    | '/admin/arrangementer'
    | '/admin/bannere'
    | '/admin/brukere'
    | '/admin/grupper'
    | '/admin/nyheter'
    | '/admin/opptak'
    | '/admin/prikker'
    | '/_app/'
    | '/admin/'
    | '/_app/galleri/$slug'
    | '/_app/grupper/$slug'
    | '/_app/playground/markdown'
    | '/_app/profil/$id'
    | '/_app/profil/me'
    | '/admin/_super-admin/api-keys'
    | '/admin/_super-admin/database'
    | '/admin/_super-admin/logs'
    | '/_app/galleri/'
    | '/_app/grupper/'
    | '/_app/profil/$id/arrangementer'
    | '/_app/profil/$id/medlemskap'
    | '/_app/profil/$id/prikker'
    | '/_app/profil/$id/sporreskjemaer'
    | '/_app/profil/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/prikker': {
      id: '/admin/prikker'
      path: '/prikker'
      fullPath: '/admin/prikker'
      preLoaderRoute: typeof AdminPrikkerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opptak': {
      id: '/admin/opptak'
      path: '/opptak'
      fullPath: '/admin/opptak'
      preLoaderRoute: typeof AdminOpptakRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nyheter': {
      id: '/admin/nyheter'
      path: '/nyheter'
      fullPath: '/admin/nyheter'
      preLoaderRoute: typeof AdminNyheterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grupper': {
      id: '/admin/grupper'
      path: '/grupper'
      fullPath: '/admin/grupper'
      preLoaderRoute: typeof AdminGrupperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brukere': {
      id: '/admin/brukere'
      path: '/brukere'
      fullPath: '/admin/brukere'
      preLoaderRoute: typeof AdminBrukereRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bannere': {
      id: '/admin/bannere'
      path: '/bannere'
      fullPath: '/admin/bannere'
      preLoaderRoute: typeof AdminBannereRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arrangementer': {
      id: '/admin/arrangementer'
      path: '/arrangementer'
      fullPath: '/admin/arrangementer'
      preLoaderRoute: typeof AdminArrangementerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/annonser': {
      id: '/admin/annonser'
      path: '/annonser'
      fullPath: '/admin/annonser'
      preLoaderRoute: typeof AdminAnnonserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_super-admin': {
      id: '/admin/_super-admin'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminSuperAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/toddel': {
      id: '/_app/toddel'
      path: '/toddel'
      fullPath: '/toddel'
      preLoaderRoute: typeof AppToddelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nyheter': {
      id: '/_app/nyheter'
      path: '/nyheter'
      fullPath: '/nyheter'
      preLoaderRoute: typeof AppNyheterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontrakt': {
      id: '/_app/kontrakt'
      path: '/kontrakt'
      fullPath: '/kontrakt'
      preLoaderRoute: typeof AppKontraktRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kokebok': {
      id: '/_app/kokebok'
      path: '/kokebok'
      fullPath: '/kokebok'
      preLoaderRoute: typeof AppKokebokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrangementer': {
      id: '/_app/arrangementer'
      path: '/arrangementer'
      fullPath: '/arrangementer'
      preLoaderRoute: typeof AppArrangementerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annonser': {
      id: '/_app/annonser'
      path: '/annonser'
      fullPath: '/annonser'
      preLoaderRoute: typeof AppAnnonserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupper/': {
      id: '/_app/grupper/'
      path: '/grupper'
      fullPath: '/grupper/'
      preLoaderRoute: typeof AppGrupperIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galleri/': {
      id: '/_app/galleri/'
      path: '/galleri'
      fullPath: '/galleri/'
      preLoaderRoute: typeof AppGalleriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/_super-admin/logs': {
      id: '/admin/_super-admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminSuperAdminLogsRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/admin/_super-admin/database': {
      id: '/admin/_super-admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminSuperAdminDatabaseRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/admin/_super-admin/api-keys': {
      id: '/admin/_super-admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminSuperAdminApiKeysRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/_app/profil/me': {
      id: '/_app/profil/me'
      path: '/profil/me'
      fullPath: '/profil/me'
      preLoaderRoute: typeof AppProfilMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/$id': {
      id: '/_app/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof AppProfilIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/markdown': {
      id: '/_app/playground/markdown'
      path: '/playground/markdown'
      fullPath: '/playground/markdown'
      preLoaderRoute: typeof AppPlaygroundMarkdownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupper/$slug': {
      id: '/_app/grupper/$slug'
      path: '/grupper/$slug'
      fullPath: '/grupper/$slug'
      preLoaderRoute: typeof AppGrupperSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galleri/$slug': {
      id: '/_app/galleri/$slug'
      path: '/galleri/$slug'
      fullPath: '/galleri/$slug'
      preLoaderRoute: typeof AppGalleriSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/$id/': {
      id: '/_app/profil/$id/'
      path: '/'
      fullPath: '/profil/$id/'
      preLoaderRoute: typeof AppProfilIdIndexRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/sporreskjemaer': {
      id: '/_app/profil/$id/sporreskjemaer'
      path: '/sporreskjemaer'
      fullPath: '/profil/$id/sporreskjemaer'
      preLoaderRoute: typeof AppProfilIdSporreskjemaerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/prikker': {
      id: '/_app/profil/$id/prikker'
      path: '/prikker'
      fullPath: '/profil/$id/prikker'
      preLoaderRoute: typeof AppProfilIdPrikkerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/medlemskap': {
      id: '/_app/profil/$id/medlemskap'
      path: '/medlemskap'
      fullPath: '/profil/$id/medlemskap'
      preLoaderRoute: typeof AppProfilIdMedlemskapRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/arrangementer': {
      id: '/_app/profil/$id/arrangementer'
      path: '/arrangementer'
      fullPath: '/profil/$id/arrangementer'
      preLoaderRoute: typeof AppProfilIdArrangementerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
  }
}

interface AppProfilIdRouteChildren {
  AppProfilIdArrangementerRoute: typeof AppProfilIdArrangementerRoute
  AppProfilIdMedlemskapRoute: typeof AppProfilIdMedlemskapRoute
  AppProfilIdPrikkerRoute: typeof AppProfilIdPrikkerRoute
  AppProfilIdSporreskjemaerRoute: typeof AppProfilIdSporreskjemaerRoute
  AppProfilIdIndexRoute: typeof AppProfilIdIndexRoute
}

const AppProfilIdRouteChildren: AppProfilIdRouteChildren = {
  AppProfilIdArrangementerRoute: AppProfilIdArrangementerRoute,
  AppProfilIdMedlemskapRoute: AppProfilIdMedlemskapRoute,
  AppProfilIdPrikkerRoute: AppProfilIdPrikkerRoute,
  AppProfilIdSporreskjemaerRoute: AppProfilIdSporreskjemaerRoute,
  AppProfilIdIndexRoute: AppProfilIdIndexRoute,
}

const AppProfilIdRouteWithChildren = AppProfilIdRoute._addFileChildren(
  AppProfilIdRouteChildren,
)

interface AppRouteChildren {
  AppAnnonserRoute: typeof AppAnnonserRoute
  AppArrangementerRoute: typeof AppArrangementerRoute
  AppKokebokRoute: typeof AppKokebokRoute
  AppKontraktRoute: typeof AppKontraktRoute
  AppNyheterRoute: typeof AppNyheterRoute
  AppToddelRoute: typeof AppToddelRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGalleriSlugRoute: typeof AppGalleriSlugRoute
  AppGrupperSlugRoute: typeof AppGrupperSlugRoute
  AppPlaygroundMarkdownRoute: typeof AppPlaygroundMarkdownRoute
  AppProfilIdRoute: typeof AppProfilIdRouteWithChildren
  AppProfilMeRoute: typeof AppProfilMeRoute
  AppGalleriIndexRoute: typeof AppGalleriIndexRoute
  AppGrupperIndexRoute: typeof AppGrupperIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnonserRoute: AppAnnonserRoute,
  AppArrangementerRoute: AppArrangementerRoute,
  AppKokebokRoute: AppKokebokRoute,
  AppKontraktRoute: AppKontraktRoute,
  AppNyheterRoute: AppNyheterRoute,
  AppToddelRoute: AppToddelRoute,
  AppIndexRoute: AppIndexRoute,
  AppGalleriSlugRoute: AppGalleriSlugRoute,
  AppGrupperSlugRoute: AppGrupperSlugRoute,
  AppPlaygroundMarkdownRoute: AppPlaygroundMarkdownRoute,
  AppProfilIdRoute: AppProfilIdRouteWithChildren,
  AppProfilMeRoute: AppProfilMeRoute,
  AppGalleriIndexRoute: AppGalleriIndexRoute,
  AppGrupperIndexRoute: AppGrupperIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminSuperAdminRouteChildren {
  AdminSuperAdminApiKeysRoute: typeof AdminSuperAdminApiKeysRoute
  AdminSuperAdminDatabaseRoute: typeof AdminSuperAdminDatabaseRoute
  AdminSuperAdminLogsRoute: typeof AdminSuperAdminLogsRoute
}

const AdminSuperAdminRouteChildren: AdminSuperAdminRouteChildren = {
  AdminSuperAdminApiKeysRoute: AdminSuperAdminApiKeysRoute,
  AdminSuperAdminDatabaseRoute: AdminSuperAdminDatabaseRoute,
  AdminSuperAdminLogsRoute: AdminSuperAdminLogsRoute,
}

const AdminSuperAdminRouteWithChildren = AdminSuperAdminRoute._addFileChildren(
  AdminSuperAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminSuperAdminRoute: typeof AdminSuperAdminRouteWithChildren
  AdminAnnonserRoute: typeof AdminAnnonserRoute
  AdminArrangementerRoute: typeof AdminArrangementerRoute
  AdminBannereRoute: typeof AdminBannereRoute
  AdminBrukereRoute: typeof AdminBrukereRoute
  AdminGrupperRoute: typeof AdminGrupperRoute
  AdminNyheterRoute: typeof AdminNyheterRoute
  AdminOpptakRoute: typeof AdminOpptakRoute
  AdminPrikkerRoute: typeof AdminPrikkerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSuperAdminRoute: AdminSuperAdminRouteWithChildren,
  AdminAnnonserRoute: AdminAnnonserRoute,
  AdminArrangementerRoute: AdminArrangementerRoute,
  AdminBannereRoute: AdminBannereRoute,
  AdminBrukereRoute: AdminBrukereRoute,
  AdminGrupperRoute: AdminGrupperRoute,
  AdminNyheterRoute: AdminNyheterRoute,
  AdminOpptakRoute: AdminOpptakRoute,
  AdminPrikkerRoute: AdminPrikkerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
