/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppToddelRouteImport } from './routes/_app/toddel'
import { Route as AppProfilRouteImport } from './routes/_app/profil'
import { Route as AppNyheterRouteImport } from './routes/_app/nyheter'
import { Route as AppKokebokRouteImport } from './routes/_app/kokebok'
import { Route as AppGrupperRouteImport } from './routes/_app/grupper'
import { Route as AppArrangementerRouteImport } from './routes/_app/arrangementer'
import { Route as AppAnnonserRouteImport } from './routes/_app/annonser'
import { Route as AppGalleriIndexRouteImport } from './routes/_app/galleri.index'
import { Route as AppGalleriSlugRouteImport } from './routes/_app/galleri.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppToddelRoute = AppToddelRouteImport.update({
  id: '/toddel',
  path: '/toddel',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppNyheterRoute = AppNyheterRouteImport.update({
  id: '/nyheter',
  path: '/nyheter',
  getParentRoute: () => AppRoute,
} as any)
const AppKokebokRoute = AppKokebokRouteImport.update({
  id: '/kokebok',
  path: '/kokebok',
  getParentRoute: () => AppRoute,
} as any)
const AppGrupperRoute = AppGrupperRouteImport.update({
  id: '/grupper',
  path: '/grupper',
  getParentRoute: () => AppRoute,
} as any)
const AppArrangementerRoute = AppArrangementerRouteImport.update({
  id: '/arrangementer',
  path: '/arrangementer',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnonserRoute = AppAnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleriIndexRoute = AppGalleriIndexRouteImport.update({
  id: '/galleri/',
  path: '/galleri/',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleriSlugRoute = AppGalleriSlugRouteImport.update({
  id: '/galleri/$slug',
  path: '/galleri/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/annonser': typeof AppAnnonserRoute
  '/arrangementer': typeof AppArrangementerRoute
  '/grupper': typeof AppGrupperRoute
  '/kokebok': typeof AppKokebokRoute
  '/nyheter': typeof AppNyheterRoute
  '/profil': typeof AppProfilRoute
  '/toddel': typeof AppToddelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/galleri/$slug': typeof AppGalleriSlugRoute
  '/galleri/': typeof AppGalleriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/annonser': typeof AppAnnonserRoute
  '/arrangementer': typeof AppArrangementerRoute
  '/grupper': typeof AppGrupperRoute
  '/kokebok': typeof AppKokebokRoute
  '/nyheter': typeof AppNyheterRoute
  '/profil': typeof AppProfilRoute
  '/toddel': typeof AppToddelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/galleri/$slug': typeof AppGalleriSlugRoute
  '/galleri': typeof AppGalleriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/annonser': typeof AppAnnonserRoute
  '/_app/arrangementer': typeof AppArrangementerRoute
  '/_app/grupper': typeof AppGrupperRoute
  '/_app/kokebok': typeof AppKokebokRoute
  '/_app/nyheter': typeof AppNyheterRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/toddel': typeof AppToddelRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/galleri/$slug': typeof AppGalleriSlugRoute
  '/_app/galleri/': typeof AppGalleriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annonser'
    | '/arrangementer'
    | '/grupper'
    | '/kokebok'
    | '/nyheter'
    | '/profil'
    | '/toddel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/galleri/$slug'
    | '/galleri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annonser'
    | '/arrangementer'
    | '/grupper'
    | '/kokebok'
    | '/nyheter'
    | '/profil'
    | '/toddel'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/galleri/$slug'
    | '/galleri'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/annonser'
    | '/_app/arrangementer'
    | '/_app/grupper'
    | '/_app/kokebok'
    | '/_app/nyheter'
    | '/_app/profil'
    | '/_app/toddel'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/galleri/$slug'
    | '/_app/galleri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/toddel': {
      id: '/_app/toddel'
      path: '/toddel'
      fullPath: '/toddel'
      preLoaderRoute: typeof AppToddelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nyheter': {
      id: '/_app/nyheter'
      path: '/nyheter'
      fullPath: '/nyheter'
      preLoaderRoute: typeof AppNyheterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kokebok': {
      id: '/_app/kokebok'
      path: '/kokebok'
      fullPath: '/kokebok'
      preLoaderRoute: typeof AppKokebokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupper': {
      id: '/_app/grupper'
      path: '/grupper'
      fullPath: '/grupper'
      preLoaderRoute: typeof AppGrupperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrangementer': {
      id: '/_app/arrangementer'
      path: '/arrangementer'
      fullPath: '/arrangementer'
      preLoaderRoute: typeof AppArrangementerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annonser': {
      id: '/_app/annonser'
      path: '/annonser'
      fullPath: '/annonser'
      preLoaderRoute: typeof AppAnnonserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galleri/': {
      id: '/_app/galleri/'
      path: '/galleri'
      fullPath: '/galleri/'
      preLoaderRoute: typeof AppGalleriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galleri/$slug': {
      id: '/_app/galleri/$slug'
      path: '/galleri/$slug'
      fullPath: '/galleri/$slug'
      preLoaderRoute: typeof AppGalleriSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnonserRoute: typeof AppAnnonserRoute
  AppArrangementerRoute: typeof AppArrangementerRoute
  AppGrupperRoute: typeof AppGrupperRoute
  AppKokebokRoute: typeof AppKokebokRoute
  AppNyheterRoute: typeof AppNyheterRoute
  AppProfilRoute: typeof AppProfilRoute
  AppToddelRoute: typeof AppToddelRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGalleriSlugRoute: typeof AppGalleriSlugRoute
  AppGalleriIndexRoute: typeof AppGalleriIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnonserRoute: AppAnnonserRoute,
  AppArrangementerRoute: AppArrangementerRoute,
  AppGrupperRoute: AppGrupperRoute,
  AppKokebokRoute: AppKokebokRoute,
  AppNyheterRoute: AppNyheterRoute,
  AppProfilRoute: AppProfilRoute,
  AppToddelRoute: AppToddelRoute,
  AppIndexRoute: AppIndexRoute,
  AppGalleriSlugRoute: AppGalleriSlugRoute,
  AppGalleriIndexRoute: AppGalleriIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
