/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DevRouteImport } from './routes/_dev'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppKokebokRouteImport } from './routes/_app/kokebok'
import { Route as AppKontraktRouteImport } from './routes/_app/kontrakt'
import { Route as AppNyStudentRouteImport } from './routes/_app/ny-student'
import { Route as AppOpptakRouteImport } from './routes/_app/opptak'
import { Route as AppPersonvernRouteImport } from './routes/_app/personvern'
import { Route as AppQrKoderRouteImport } from './routes/_app/qr-koder'
import { Route as AppSoknaderRouteImport } from './routes/_app/soknader'
import { Route as AppToddelRouteImport } from './routes/_app/toddel'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthKobleFeideRouteImport } from './routes/_auth/koble-feide'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthVelgPassordRouteImport } from './routes/_auth/velg-passord'
import { Route as DevFormTestRouteImport } from './routes/_dev/form-test'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSuperAdminRouteImport } from './routes/admin/_super-admin'
import { Route as AdminAnnonserRouteImport } from './routes/admin/annonser'
import { Route as AdminBannereRouteImport } from './routes/admin/bannere'
import { Route as AdminBrukereRouteImport } from './routes/admin/brukere'
import { Route as AdminGalleriRouteImport } from './routes/admin/galleri'
import { Route as AdminGrupperRouteImport } from './routes/admin/grupper'
import { Route as AdminKontaktskjemaRouteImport } from './routes/admin/kontaktskjema'
import { Route as AdminNyheterRouteImport } from './routes/admin/nyheter'
import { Route as AdminOpptakRouteImport } from './routes/admin/opptak'
import { Route as AdminPrikkerRouteImport } from './routes/admin/prikker'
import { Route as AdminRollerRouteImport } from './routes/admin/roller'
import { Route as AdminSoknaderRouteImport } from './routes/admin/soknader'
import { Route as AdminToddelRouteImport } from './routes/admin/toddel'
import { Route as AppAnnonserIndexRouteImport } from './routes/_app/annonser.index'
import { Route as AppAnnonserSlugRouteImport } from './routes/_app/annonser.$slug'
import { Route as AppArrangementerIndexRouteImport } from './routes/_app/arrangementer.index'
import { Route as AppArrangementerSlugRouteImport } from './routes/_app/arrangementer.$slug'
import { Route as AppBedriftIndexRouteImport } from './routes/_app/bedrift.index'
import { Route as AppBedriftStudieneRouteImport } from './routes/_app/bedrift.studiene'
import { Route as AppGalleriIndexRouteImport } from './routes/_app/galleri.index'
import { Route as AppGalleriSlugRouteImport } from './routes/_app/galleri.$slug'
import { Route as AppGrupperIndexRouteImport } from './routes/_app/grupper.index'
import { Route as AppGrupperSlugRouteImport } from './routes/_app/grupper.$slug'
import { Route as AppMotetidIndexRouteImport } from './routes/_app/motetid.index'
import { Route as AppMotetidSlugRouteImport } from './routes/_app/motetid.$slug'
import { Route as AppMotetidNyRouteImport } from './routes/_app/motetid.ny'
import { Route as AppNyheterIndexRouteImport } from './routes/_app/nyheter.index'
import { Route as AppNyheterSlugRouteImport } from './routes/_app/nyheter.$slug'
import { Route as AppPlaygroundMarkdownRouteImport } from './routes/_app/playground.markdown'
import { Route as AppProfilIdRouteImport } from './routes/_app/profil/$id'
import { Route as AppSporreskjemaIdRouteImport } from './routes/_app/sporreskjema.$id'
import { Route as AuthOauthConsentRouteImport } from './routes/_auth/oauth/consent'
import { Route as AdminSuperAdminApiKeysRouteImport } from './routes/admin/_super-admin/api-keys'
import { Route as AdminSuperAdminDatabaseRouteImport } from './routes/admin/_super-admin/database'
import { Route as AdminSuperAdminLogsRouteImport } from './routes/admin/_super-admin/logs'
import { Route as AdminSuperAdminOauthClientsRouteImport } from './routes/admin/_super-admin/oauth-clients'
import { Route as AdminArrangementerIndexRouteImport } from './routes/admin/arrangementer.index'
import { Route as AdminArrangementerEventIdRouteImport } from './routes/admin/arrangementer.$eventId'
import { Route as AdminArrangementerNyRouteImport } from './routes/admin/arrangementer.ny'
import { Route as AppProfilIdIndexRouteImport } from './routes/_app/profil/$id/index'
import { Route as AppProfilIdArrangementerRouteImport } from './routes/_app/profil/$id/arrangementer'
import { Route as AppProfilIdInnstillingerRouteImport } from './routes/_app/profil/$id/innstillinger'
import { Route as AppProfilIdMedlemskapRouteImport } from './routes/_app/profil/$id/medlemskap'
import { Route as AppProfilIdPrikkerRouteImport } from './routes/_app/profil/$id/prikker'
import { Route as AppProfilIdSporreskjemaerRouteImport } from './routes/_app/profil/$id/sporreskjemaer'
import { Route as AppSporreskjemaIdSvarRouteImport } from './routes/_app/sporreskjema.$id_.svar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/_dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppKokebokRoute = AppKokebokRouteImport.update({
  id: '/kokebok',
  path: '/kokebok',
  getParentRoute: () => AppRoute,
} as any)
const AppKontraktRoute = AppKontraktRouteImport.update({
  id: '/kontrakt',
  path: '/kontrakt',
  getParentRoute: () => AppRoute,
} as any)
const AppNyStudentRoute = AppNyStudentRouteImport.update({
  id: '/ny-student',
  path: '/ny-student',
  getParentRoute: () => AppRoute,
} as any)
const AppOpptakRoute = AppOpptakRouteImport.update({
  id: '/opptak',
  path: '/opptak',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonvernRoute = AppPersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => AppRoute,
} as any)
const AppQrKoderRoute = AppQrKoderRouteImport.update({
  id: '/qr-koder',
  path: '/qr-koder',
  getParentRoute: () => AppRoute,
} as any)
const AppSoknaderRoute = AppSoknaderRouteImport.update({
  id: '/soknader',
  path: '/soknader',
  getParentRoute: () => AppRoute,
} as any)
const AppToddelRoute = AppToddelRouteImport.update({
  id: '/toddel',
  path: '/toddel',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKobleFeideRoute = AuthKobleFeideRouteImport.update({
  id: '/koble-feide',
  path: '/koble-feide',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVelgPassordRoute = AuthVelgPassordRouteImport.update({
  id: '/velg-passord',
  path: '/velg-passord',
  getParentRoute: () => AuthRoute,
} as any)
const DevFormTestRoute = DevFormTestRouteImport.update({
  id: '/form-test',
  path: '/form-test',
  getParentRoute: () => DevRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuperAdminRoute = AdminSuperAdminRouteImport.update({
  id: '/_super-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnonserRoute = AdminAnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannereRoute = AdminBannereRouteImport.update({
  id: '/bannere',
  path: '/bannere',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrukereRoute = AdminBrukereRouteImport.update({
  id: '/brukere',
  path: '/brukere',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleriRoute = AdminGalleriRouteImport.update({
  id: '/galleri',
  path: '/galleri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGrupperRoute = AdminGrupperRouteImport.update({
  id: '/grupper',
  path: '/grupper',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKontaktskjemaRoute = AdminKontaktskjemaRouteImport.update({
  id: '/kontaktskjema',
  path: '/kontaktskjema',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNyheterRoute = AdminNyheterRouteImport.update({
  id: '/nyheter',
  path: '/nyheter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpptakRoute = AdminOpptakRouteImport.update({
  id: '/opptak',
  path: '/opptak',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrikkerRoute = AdminPrikkerRouteImport.update({
  id: '/prikker',
  path: '/prikker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRollerRoute = AdminRollerRouteImport.update({
  id: '/roller',
  path: '/roller',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoknaderRoute = AdminSoknaderRouteImport.update({
  id: '/soknader',
  path: '/soknader',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToddelRoute = AdminToddelRouteImport.update({
  id: '/toddel',
  path: '/toddel',
  getParentRoute: () => AdminRoute,
} as any)
const AppAnnonserIndexRoute = AppAnnonserIndexRouteImport.update({
  id: '/annonser/',
  path: '/annonser/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnonserSlugRoute = AppAnnonserSlugRouteImport.update({
  id: '/annonser/$slug',
  path: '/annonser/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppArrangementerIndexRoute = AppArrangementerIndexRouteImport.update({
  id: '/arrangementer/',
  path: '/arrangementer/',
  getParentRoute: () => AppRoute,
} as any)
const AppArrangementerSlugRoute = AppArrangementerSlugRouteImport.update({
  id: '/arrangementer/$slug',
  path: '/arrangementer/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppBedriftIndexRoute = AppBedriftIndexRouteImport.update({
  id: '/bedrift/',
  path: '/bedrift/',
  getParentRoute: () => AppRoute,
} as any)
const AppBedriftStudieneRoute = AppBedriftStudieneRouteImport.update({
  id: '/bedrift/studiene',
  path: '/bedrift/studiene',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleriIndexRoute = AppGalleriIndexRouteImport.update({
  id: '/galleri/',
  path: '/galleri/',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleriSlugRoute = AppGalleriSlugRouteImport.update({
  id: '/galleri/$slug',
  path: '/galleri/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppGrupperIndexRoute = AppGrupperIndexRouteImport.update({
  id: '/grupper/',
  path: '/grupper/',
  getParentRoute: () => AppRoute,
} as any)
const AppGrupperSlugRoute = AppGrupperSlugRouteImport.update({
  id: '/grupper/$slug',
  path: '/grupper/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppMotetidIndexRoute = AppMotetidIndexRouteImport.update({
  id: '/motetid/',
  path: '/motetid/',
  getParentRoute: () => AppRoute,
} as any)
const AppMotetidSlugRoute = AppMotetidSlugRouteImport.update({
  id: '/motetid/$slug',
  path: '/motetid/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppMotetidNyRoute = AppMotetidNyRouteImport.update({
  id: '/motetid/ny',
  path: '/motetid/ny',
  getParentRoute: () => AppRoute,
} as any)
const AppNyheterIndexRoute = AppNyheterIndexRouteImport.update({
  id: '/nyheter/',
  path: '/nyheter/',
  getParentRoute: () => AppRoute,
} as any)
const AppNyheterSlugRoute = AppNyheterSlugRouteImport.update({
  id: '/nyheter/$slug',
  path: '/nyheter/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundMarkdownRoute = AppPlaygroundMarkdownRouteImport.update({
  id: '/playground/markdown',
  path: '/playground/markdown',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilIdRoute = AppProfilIdRouteImport.update({
  id: '/profil/$id',
  path: '/profil/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSporreskjemaIdRoute = AppSporreskjemaIdRouteImport.update({
  id: '/sporreskjema/$id',
  path: '/sporreskjema/$id',
  getParentRoute: () => AppRoute,
} as any)
const AuthOauthConsentRoute = AuthOauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSuperAdminApiKeysRoute = AdminSuperAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminSuperAdminRoute,
} as any)
const AdminSuperAdminDatabaseRoute = AdminSuperAdminDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AdminSuperAdminRoute,
} as any)
const AdminSuperAdminLogsRoute = AdminSuperAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminSuperAdminRoute,
} as any)
const AdminSuperAdminOauthClientsRoute =
  AdminSuperAdminOauthClientsRouteImport.update({
    id: '/oauth-clients',
    path: '/oauth-clients',
    getParentRoute: () => AdminSuperAdminRoute,
  } as any)
const AdminArrangementerIndexRoute = AdminArrangementerIndexRouteImport.update({
  id: '/arrangementer/',
  path: '/arrangementer/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArrangementerEventIdRoute =
  AdminArrangementerEventIdRouteImport.update({
    id: '/arrangementer/$eventId',
    path: '/arrangementer/$eventId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminArrangementerNyRoute = AdminArrangementerNyRouteImport.update({
  id: '/arrangementer/ny',
  path: '/arrangementer/ny',
  getParentRoute: () => AdminRoute,
} as any)
const AppProfilIdIndexRoute = AppProfilIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfilIdRoute,
} as any)
const AppProfilIdArrangementerRoute =
  AppProfilIdArrangementerRouteImport.update({
    id: '/arrangementer',
    path: '/arrangementer',
    getParentRoute: () => AppProfilIdRoute,
  } as any)
const AppProfilIdInnstillingerRoute =
  AppProfilIdInnstillingerRouteImport.update({
    id: '/innstillinger',
    path: '/innstillinger',
    getParentRoute: () => AppProfilIdRoute,
  } as any)
const AppProfilIdMedlemskapRoute = AppProfilIdMedlemskapRouteImport.update({
  id: '/medlemskap',
  path: '/medlemskap',
  getParentRoute: () => AppProfilIdRoute,
} as any)
const AppProfilIdPrikkerRoute = AppProfilIdPrikkerRouteImport.update({
  id: '/prikker',
  path: '/prikker',
  getParentRoute: () => AppProfilIdRoute,
} as any)
const AppProfilIdSporreskjemaerRoute =
  AppProfilIdSporreskjemaerRouteImport.update({
    id: '/sporreskjemaer',
    path: '/sporreskjemaer',
    getParentRoute: () => AppProfilIdRoute,
  } as any)
const AppSporreskjemaIdSvarRoute = AppSporreskjemaIdSvarRouteImport.update({
  id: '/sporreskjema/$id_/svar',
  path: '/sporreskjema/$id/svar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kokebok': typeof AppKokebokRoute
  '/kontrakt': typeof AppKontraktRoute
  '/ny-student': typeof AppNyStudentRoute
  '/opptak': typeof AppOpptakRoute
  '/personvern': typeof AppPersonvernRoute
  '/qr-koder': typeof AppQrKoderRoute
  '/soknader': typeof AppSoknaderRoute
  '/toddel': typeof AppToddelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/koble-feide': typeof AuthKobleFeideRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/velg-passord': typeof AuthVelgPassordRoute
  '/form-test': typeof DevFormTestRoute
  '/admin/annonser': typeof AdminAnnonserRoute
  '/admin/bannere': typeof AdminBannereRoute
  '/admin/brukere': typeof AdminBrukereRoute
  '/admin/galleri': typeof AdminGalleriRoute
  '/admin/grupper': typeof AdminGrupperRoute
  '/admin/kontaktskjema': typeof AdminKontaktskjemaRoute
  '/admin/nyheter': typeof AdminNyheterRoute
  '/admin/opptak': typeof AdminOpptakRoute
  '/admin/prikker': typeof AdminPrikkerRoute
  '/admin/roller': typeof AdminRollerRoute
  '/admin/soknader': typeof AdminSoknaderRoute
  '/admin/toddel': typeof AdminToddelRoute
  '/admin/': typeof AdminIndexRoute
  '/annonser/$slug': typeof AppAnnonserSlugRoute
  '/arrangementer/$slug': typeof AppArrangementerSlugRoute
  '/bedrift/studiene': typeof AppBedriftStudieneRoute
  '/galleri/$slug': typeof AppGalleriSlugRoute
  '/grupper/$slug': typeof AppGrupperSlugRoute
  '/motetid/$slug': typeof AppMotetidSlugRoute
  '/motetid/ny': typeof AppMotetidNyRoute
  '/nyheter/$slug': typeof AppNyheterSlugRoute
  '/playground/markdown': typeof AppPlaygroundMarkdownRoute
  '/profil/$id': typeof AppProfilIdRouteWithChildren
  '/sporreskjema/$id': typeof AppSporreskjemaIdRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/admin/api-keys': typeof AdminSuperAdminApiKeysRoute
  '/admin/database': typeof AdminSuperAdminDatabaseRoute
  '/admin/logs': typeof AdminSuperAdminLogsRoute
  '/admin/oauth-clients': typeof AdminSuperAdminOauthClientsRoute
  '/admin/arrangementer/$eventId': typeof AdminArrangementerEventIdRoute
  '/admin/arrangementer/ny': typeof AdminArrangementerNyRoute
  '/annonser/': typeof AppAnnonserIndexRoute
  '/arrangementer/': typeof AppArrangementerIndexRoute
  '/bedrift/': typeof AppBedriftIndexRoute
  '/galleri/': typeof AppGalleriIndexRoute
  '/grupper/': typeof AppGrupperIndexRoute
  '/motetid/': typeof AppMotetidIndexRoute
  '/nyheter/': typeof AppNyheterIndexRoute
  '/admin/arrangementer/': typeof AdminArrangementerIndexRoute
  '/profil/$id/arrangementer': typeof AppProfilIdArrangementerRoute
  '/profil/$id/innstillinger': typeof AppProfilIdInnstillingerRoute
  '/profil/$id/medlemskap': typeof AppProfilIdMedlemskapRoute
  '/profil/$id/prikker': typeof AppProfilIdPrikkerRoute
  '/profil/$id/sporreskjemaer': typeof AppProfilIdSporreskjemaerRoute
  '/sporreskjema/$id/svar': typeof AppSporreskjemaIdSvarRoute
  '/profil/$id/': typeof AppProfilIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/kokebok': typeof AppKokebokRoute
  '/kontrakt': typeof AppKontraktRoute
  '/ny-student': typeof AppNyStudentRoute
  '/opptak': typeof AppOpptakRoute
  '/personvern': typeof AppPersonvernRoute
  '/qr-koder': typeof AppQrKoderRoute
  '/soknader': typeof AppSoknaderRoute
  '/toddel': typeof AppToddelRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/koble-feide': typeof AuthKobleFeideRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/velg-passord': typeof AuthVelgPassordRoute
  '/form-test': typeof DevFormTestRoute
  '/admin': typeof AdminIndexRoute
  '/admin/annonser': typeof AdminAnnonserRoute
  '/admin/bannere': typeof AdminBannereRoute
  '/admin/brukere': typeof AdminBrukereRoute
  '/admin/galleri': typeof AdminGalleriRoute
  '/admin/grupper': typeof AdminGrupperRoute
  '/admin/kontaktskjema': typeof AdminKontaktskjemaRoute
  '/admin/nyheter': typeof AdminNyheterRoute
  '/admin/opptak': typeof AdminOpptakRoute
  '/admin/prikker': typeof AdminPrikkerRoute
  '/admin/roller': typeof AdminRollerRoute
  '/admin/soknader': typeof AdminSoknaderRoute
  '/admin/toddel': typeof AdminToddelRoute
  '/annonser/$slug': typeof AppAnnonserSlugRoute
  '/arrangementer/$slug': typeof AppArrangementerSlugRoute
  '/bedrift/studiene': typeof AppBedriftStudieneRoute
  '/galleri/$slug': typeof AppGalleriSlugRoute
  '/grupper/$slug': typeof AppGrupperSlugRoute
  '/motetid/$slug': typeof AppMotetidSlugRoute
  '/motetid/ny': typeof AppMotetidNyRoute
  '/nyheter/$slug': typeof AppNyheterSlugRoute
  '/playground/markdown': typeof AppPlaygroundMarkdownRoute
  '/sporreskjema/$id': typeof AppSporreskjemaIdRoute
  '/oauth/consent': typeof AuthOauthConsentRoute
  '/admin/api-keys': typeof AdminSuperAdminApiKeysRoute
  '/admin/database': typeof AdminSuperAdminDatabaseRoute
  '/admin/logs': typeof AdminSuperAdminLogsRoute
  '/admin/oauth-clients': typeof AdminSuperAdminOauthClientsRoute
  '/admin/arrangementer/$eventId': typeof AdminArrangementerEventIdRoute
  '/admin/arrangementer/ny': typeof AdminArrangementerNyRoute
  '/annonser': typeof AppAnnonserIndexRoute
  '/arrangementer': typeof AppArrangementerIndexRoute
  '/bedrift': typeof AppBedriftIndexRoute
  '/galleri': typeof AppGalleriIndexRoute
  '/grupper': typeof AppGrupperIndexRoute
  '/motetid': typeof AppMotetidIndexRoute
  '/nyheter': typeof AppNyheterIndexRoute
  '/admin/arrangementer': typeof AdminArrangementerIndexRoute
  '/profil/$id/arrangementer': typeof AppProfilIdArrangementerRoute
  '/profil/$id/innstillinger': typeof AppProfilIdInnstillingerRoute
  '/profil/$id/medlemskap': typeof AppProfilIdMedlemskapRoute
  '/profil/$id/prikker': typeof AppProfilIdPrikkerRoute
  '/profil/$id/sporreskjemaer': typeof AppProfilIdSporreskjemaerRoute
  '/sporreskjema/$id/svar': typeof AppSporreskjemaIdSvarRoute
  '/profil/$id': typeof AppProfilIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_dev': typeof DevRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/kokebok': typeof AppKokebokRoute
  '/_app/kontrakt': typeof AppKontraktRoute
  '/_app/ny-student': typeof AppNyStudentRoute
  '/_app/opptak': typeof AppOpptakRoute
  '/_app/personvern': typeof AppPersonvernRoute
  '/_app/qr-koder': typeof AppQrKoderRoute
  '/_app/soknader': typeof AppSoknaderRoute
  '/_app/toddel': typeof AppToddelRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/koble-feide': typeof AuthKobleFeideRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/velg-passord': typeof AuthVelgPassordRoute
  '/_dev/form-test': typeof DevFormTestRoute
  '/admin/_super-admin': typeof AdminSuperAdminRouteWithChildren
  '/admin/annonser': typeof AdminAnnonserRoute
  '/admin/bannere': typeof AdminBannereRoute
  '/admin/brukere': typeof AdminBrukereRoute
  '/admin/galleri': typeof AdminGalleriRoute
  '/admin/grupper': typeof AdminGrupperRoute
  '/admin/kontaktskjema': typeof AdminKontaktskjemaRoute
  '/admin/nyheter': typeof AdminNyheterRoute
  '/admin/opptak': typeof AdminOpptakRoute
  '/admin/prikker': typeof AdminPrikkerRoute
  '/admin/roller': typeof AdminRollerRoute
  '/admin/soknader': typeof AdminSoknaderRoute
  '/admin/toddel': typeof AdminToddelRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/annonser/$slug': typeof AppAnnonserSlugRoute
  '/_app/arrangementer/$slug': typeof AppArrangementerSlugRoute
  '/_app/bedrift/studiene': typeof AppBedriftStudieneRoute
  '/_app/galleri/$slug': typeof AppGalleriSlugRoute
  '/_app/grupper/$slug': typeof AppGrupperSlugRoute
  '/_app/motetid/$slug': typeof AppMotetidSlugRoute
  '/_app/motetid/ny': typeof AppMotetidNyRoute
  '/_app/nyheter/$slug': typeof AppNyheterSlugRoute
  '/_app/playground/markdown': typeof AppPlaygroundMarkdownRoute
  '/_app/profil/$id': typeof AppProfilIdRouteWithChildren
  '/_app/sporreskjema/$id': typeof AppSporreskjemaIdRoute
  '/_auth/oauth/consent': typeof AuthOauthConsentRoute
  '/admin/_super-admin/api-keys': typeof AdminSuperAdminApiKeysRoute
  '/admin/_super-admin/database': typeof AdminSuperAdminDatabaseRoute
  '/admin/_super-admin/logs': typeof AdminSuperAdminLogsRoute
  '/admin/_super-admin/oauth-clients': typeof AdminSuperAdminOauthClientsRoute
  '/admin/arrangementer/$eventId': typeof AdminArrangementerEventIdRoute
  '/admin/arrangementer/ny': typeof AdminArrangementerNyRoute
  '/_app/annonser/': typeof AppAnnonserIndexRoute
  '/_app/arrangementer/': typeof AppArrangementerIndexRoute
  '/_app/bedrift/': typeof AppBedriftIndexRoute
  '/_app/galleri/': typeof AppGalleriIndexRoute
  '/_app/grupper/': typeof AppGrupperIndexRoute
  '/_app/motetid/': typeof AppMotetidIndexRoute
  '/_app/nyheter/': typeof AppNyheterIndexRoute
  '/admin/arrangementer/': typeof AdminArrangementerIndexRoute
  '/_app/profil/$id/arrangementer': typeof AppProfilIdArrangementerRoute
  '/_app/profil/$id/innstillinger': typeof AppProfilIdInnstillingerRoute
  '/_app/profil/$id/medlemskap': typeof AppProfilIdMedlemskapRoute
  '/_app/profil/$id/prikker': typeof AppProfilIdPrikkerRoute
  '/_app/profil/$id/sporreskjemaer': typeof AppProfilIdSporreskjemaerRoute
  '/_app/sporreskjema/$id_/svar': typeof AppSporreskjemaIdSvarRoute
  '/_app/profil/$id/': typeof AppProfilIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kokebok'
    | '/kontrakt'
    | '/ny-student'
    | '/opptak'
    | '/personvern'
    | '/qr-koder'
    | '/soknader'
    | '/toddel'
    | '/forgot-password'
    | '/koble-feide'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/velg-passord'
    | '/form-test'
    | '/admin/annonser'
    | '/admin/bannere'
    | '/admin/brukere'
    | '/admin/galleri'
    | '/admin/grupper'
    | '/admin/kontaktskjema'
    | '/admin/nyheter'
    | '/admin/opptak'
    | '/admin/prikker'
    | '/admin/roller'
    | '/admin/soknader'
    | '/admin/toddel'
    | '/admin/'
    | '/annonser/$slug'
    | '/arrangementer/$slug'
    | '/bedrift/studiene'
    | '/galleri/$slug'
    | '/grupper/$slug'
    | '/motetid/$slug'
    | '/motetid/ny'
    | '/nyheter/$slug'
    | '/playground/markdown'
    | '/profil/$id'
    | '/sporreskjema/$id'
    | '/oauth/consent'
    | '/admin/api-keys'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/oauth-clients'
    | '/admin/arrangementer/$eventId'
    | '/admin/arrangementer/ny'
    | '/annonser/'
    | '/arrangementer/'
    | '/bedrift/'
    | '/galleri/'
    | '/grupper/'
    | '/motetid/'
    | '/nyheter/'
    | '/admin/arrangementer/'
    | '/profil/$id/arrangementer'
    | '/profil/$id/innstillinger'
    | '/profil/$id/medlemskap'
    | '/profil/$id/prikker'
    | '/profil/$id/sporreskjemaer'
    | '/sporreskjema/$id/svar'
    | '/profil/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kokebok'
    | '/kontrakt'
    | '/ny-student'
    | '/opptak'
    | '/personvern'
    | '/qr-koder'
    | '/soknader'
    | '/toddel'
    | '/forgot-password'
    | '/koble-feide'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/velg-passord'
    | '/form-test'
    | '/admin'
    | '/admin/annonser'
    | '/admin/bannere'
    | '/admin/brukere'
    | '/admin/galleri'
    | '/admin/grupper'
    | '/admin/kontaktskjema'
    | '/admin/nyheter'
    | '/admin/opptak'
    | '/admin/prikker'
    | '/admin/roller'
    | '/admin/soknader'
    | '/admin/toddel'
    | '/annonser/$slug'
    | '/arrangementer/$slug'
    | '/bedrift/studiene'
    | '/galleri/$slug'
    | '/grupper/$slug'
    | '/motetid/$slug'
    | '/motetid/ny'
    | '/nyheter/$slug'
    | '/playground/markdown'
    | '/sporreskjema/$id'
    | '/oauth/consent'
    | '/admin/api-keys'
    | '/admin/database'
    | '/admin/logs'
    | '/admin/oauth-clients'
    | '/admin/arrangementer/$eventId'
    | '/admin/arrangementer/ny'
    | '/annonser'
    | '/arrangementer'
    | '/bedrift'
    | '/galleri'
    | '/grupper'
    | '/motetid'
    | '/nyheter'
    | '/admin/arrangementer'
    | '/profil/$id/arrangementer'
    | '/profil/$id/innstillinger'
    | '/profil/$id/medlemskap'
    | '/profil/$id/prikker'
    | '/profil/$id/sporreskjemaer'
    | '/sporreskjema/$id/svar'
    | '/profil/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_dev'
    | '/admin'
    | '/_app/kokebok'
    | '/_app/kontrakt'
    | '/_app/ny-student'
    | '/_app/opptak'
    | '/_app/personvern'
    | '/_app/qr-koder'
    | '/_app/soknader'
    | '/_app/toddel'
    | '/_auth/forgot-password'
    | '/_auth/koble-feide'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/velg-passord'
    | '/_dev/form-test'
    | '/admin/_super-admin'
    | '/admin/annonser'
    | '/admin/bannere'
    | '/admin/brukere'
    | '/admin/galleri'
    | '/admin/grupper'
    | '/admin/kontaktskjema'
    | '/admin/nyheter'
    | '/admin/opptak'
    | '/admin/prikker'
    | '/admin/roller'
    | '/admin/soknader'
    | '/admin/toddel'
    | '/_app/'
    | '/admin/'
    | '/_app/annonser/$slug'
    | '/_app/arrangementer/$slug'
    | '/_app/bedrift/studiene'
    | '/_app/galleri/$slug'
    | '/_app/grupper/$slug'
    | '/_app/motetid/$slug'
    | '/_app/motetid/ny'
    | '/_app/nyheter/$slug'
    | '/_app/playground/markdown'
    | '/_app/profil/$id'
    | '/_app/sporreskjema/$id'
    | '/_auth/oauth/consent'
    | '/admin/_super-admin/api-keys'
    | '/admin/_super-admin/database'
    | '/admin/_super-admin/logs'
    | '/admin/_super-admin/oauth-clients'
    | '/admin/arrangementer/$eventId'
    | '/admin/arrangementer/ny'
    | '/_app/annonser/'
    | '/_app/arrangementer/'
    | '/_app/bedrift/'
    | '/_app/galleri/'
    | '/_app/grupper/'
    | '/_app/motetid/'
    | '/_app/nyheter/'
    | '/admin/arrangementer/'
    | '/_app/profil/$id/arrangementer'
    | '/_app/profil/$id/innstillinger'
    | '/_app/profil/$id/medlemskap'
    | '/_app/profil/$id/prikker'
    | '/_app/profil/$id/sporreskjemaer'
    | '/_app/sporreskjema/$id_/svar'
    | '/_app/profil/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev': {
      id: '/_dev'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kokebok': {
      id: '/_app/kokebok'
      path: '/kokebok'
      fullPath: '/kokebok'
      preLoaderRoute: typeof AppKokebokRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kontrakt': {
      id: '/_app/kontrakt'
      path: '/kontrakt'
      fullPath: '/kontrakt'
      preLoaderRoute: typeof AppKontraktRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ny-student': {
      id: '/_app/ny-student'
      path: '/ny-student'
      fullPath: '/ny-student'
      preLoaderRoute: typeof AppNyStudentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opptak': {
      id: '/_app/opptak'
      path: '/opptak'
      fullPath: '/opptak'
      preLoaderRoute: typeof AppOpptakRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personvern': {
      id: '/_app/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof AppPersonvernRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr-koder': {
      id: '/_app/qr-koder'
      path: '/qr-koder'
      fullPath: '/qr-koder'
      preLoaderRoute: typeof AppQrKoderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/soknader': {
      id: '/_app/soknader'
      path: '/soknader'
      fullPath: '/soknader'
      preLoaderRoute: typeof AppSoknaderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/toddel': {
      id: '/_app/toddel'
      path: '/toddel'
      fullPath: '/toddel'
      preLoaderRoute: typeof AppToddelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/koble-feide': {
      id: '/_auth/koble-feide'
      path: '/koble-feide'
      fullPath: '/koble-feide'
      preLoaderRoute: typeof AuthKobleFeideRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/velg-passord': {
      id: '/_auth/velg-passord'
      path: '/velg-passord'
      fullPath: '/velg-passord'
      preLoaderRoute: typeof AuthVelgPassordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dev/form-test': {
      id: '/_dev/form-test'
      path: '/form-test'
      fullPath: '/form-test'
      preLoaderRoute: typeof DevFormTestRouteImport
      parentRoute: typeof DevRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_super-admin': {
      id: '/admin/_super-admin'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminSuperAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/annonser': {
      id: '/admin/annonser'
      path: '/annonser'
      fullPath: '/admin/annonser'
      preLoaderRoute: typeof AdminAnnonserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bannere': {
      id: '/admin/bannere'
      path: '/bannere'
      fullPath: '/admin/bannere'
      preLoaderRoute: typeof AdminBannereRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brukere': {
      id: '/admin/brukere'
      path: '/brukere'
      fullPath: '/admin/brukere'
      preLoaderRoute: typeof AdminBrukereRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galleri': {
      id: '/admin/galleri'
      path: '/galleri'
      fullPath: '/admin/galleri'
      preLoaderRoute: typeof AdminGalleriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grupper': {
      id: '/admin/grupper'
      path: '/grupper'
      fullPath: '/admin/grupper'
      preLoaderRoute: typeof AdminGrupperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kontaktskjema': {
      id: '/admin/kontaktskjema'
      path: '/kontaktskjema'
      fullPath: '/admin/kontaktskjema'
      preLoaderRoute: typeof AdminKontaktskjemaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nyheter': {
      id: '/admin/nyheter'
      path: '/nyheter'
      fullPath: '/admin/nyheter'
      preLoaderRoute: typeof AdminNyheterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opptak': {
      id: '/admin/opptak'
      path: '/opptak'
      fullPath: '/admin/opptak'
      preLoaderRoute: typeof AdminOpptakRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prikker': {
      id: '/admin/prikker'
      path: '/prikker'
      fullPath: '/admin/prikker'
      preLoaderRoute: typeof AdminPrikkerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roller': {
      id: '/admin/roller'
      path: '/roller'
      fullPath: '/admin/roller'
      preLoaderRoute: typeof AdminRollerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/soknader': {
      id: '/admin/soknader'
      path: '/soknader'
      fullPath: '/admin/soknader'
      preLoaderRoute: typeof AdminSoknaderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/toddel': {
      id: '/admin/toddel'
      path: '/toddel'
      fullPath: '/admin/toddel'
      preLoaderRoute: typeof AdminToddelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/annonser/': {
      id: '/_app/annonser/'
      path: '/annonser'
      fullPath: '/annonser/'
      preLoaderRoute: typeof AppAnnonserIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/annonser/$slug': {
      id: '/_app/annonser/$slug'
      path: '/annonser/$slug'
      fullPath: '/annonser/$slug'
      preLoaderRoute: typeof AppAnnonserSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrangementer/': {
      id: '/_app/arrangementer/'
      path: '/arrangementer'
      fullPath: '/arrangementer/'
      preLoaderRoute: typeof AppArrangementerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arrangementer/$slug': {
      id: '/_app/arrangementer/$slug'
      path: '/arrangementer/$slug'
      fullPath: '/arrangementer/$slug'
      preLoaderRoute: typeof AppArrangementerSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bedrift/': {
      id: '/_app/bedrift/'
      path: '/bedrift'
      fullPath: '/bedrift/'
      preLoaderRoute: typeof AppBedriftIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bedrift/studiene': {
      id: '/_app/bedrift/studiene'
      path: '/bedrift/studiene'
      fullPath: '/bedrift/studiene'
      preLoaderRoute: typeof AppBedriftStudieneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galleri/': {
      id: '/_app/galleri/'
      path: '/galleri'
      fullPath: '/galleri/'
      preLoaderRoute: typeof AppGalleriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/galleri/$slug': {
      id: '/_app/galleri/$slug'
      path: '/galleri/$slug'
      fullPath: '/galleri/$slug'
      preLoaderRoute: typeof AppGalleriSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupper/': {
      id: '/_app/grupper/'
      path: '/grupper'
      fullPath: '/grupper/'
      preLoaderRoute: typeof AppGrupperIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupper/$slug': {
      id: '/_app/grupper/$slug'
      path: '/grupper/$slug'
      fullPath: '/grupper/$slug'
      preLoaderRoute: typeof AppGrupperSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motetid/': {
      id: '/_app/motetid/'
      path: '/motetid'
      fullPath: '/motetid/'
      preLoaderRoute: typeof AppMotetidIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motetid/$slug': {
      id: '/_app/motetid/$slug'
      path: '/motetid/$slug'
      fullPath: '/motetid/$slug'
      preLoaderRoute: typeof AppMotetidSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motetid/ny': {
      id: '/_app/motetid/ny'
      path: '/motetid/ny'
      fullPath: '/motetid/ny'
      preLoaderRoute: typeof AppMotetidNyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nyheter/': {
      id: '/_app/nyheter/'
      path: '/nyheter'
      fullPath: '/nyheter/'
      preLoaderRoute: typeof AppNyheterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nyheter/$slug': {
      id: '/_app/nyheter/$slug'
      path: '/nyheter/$slug'
      fullPath: '/nyheter/$slug'
      preLoaderRoute: typeof AppNyheterSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playground/markdown': {
      id: '/_app/playground/markdown'
      path: '/playground/markdown'
      fullPath: '/playground/markdown'
      preLoaderRoute: typeof AppPlaygroundMarkdownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil/$id': {
      id: '/_app/profil/$id'
      path: '/profil/$id'
      fullPath: '/profil/$id'
      preLoaderRoute: typeof AppProfilIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sporreskjema/$id': {
      id: '/_app/sporreskjema/$id'
      path: '/sporreskjema/$id'
      fullPath: '/sporreskjema/$id'
      preLoaderRoute: typeof AppSporreskjemaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/oauth/consent': {
      id: '/_auth/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof AuthOauthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/_super-admin/api-keys': {
      id: '/admin/_super-admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminSuperAdminApiKeysRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/admin/_super-admin/database': {
      id: '/admin/_super-admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AdminSuperAdminDatabaseRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/admin/_super-admin/logs': {
      id: '/admin/_super-admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminSuperAdminLogsRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/admin/_super-admin/oauth-clients': {
      id: '/admin/_super-admin/oauth-clients'
      path: '/oauth-clients'
      fullPath: '/admin/oauth-clients'
      preLoaderRoute: typeof AdminSuperAdminOauthClientsRouteImport
      parentRoute: typeof AdminSuperAdminRoute
    }
    '/admin/arrangementer/': {
      id: '/admin/arrangementer/'
      path: '/arrangementer'
      fullPath: '/admin/arrangementer/'
      preLoaderRoute: typeof AdminArrangementerIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arrangementer/$eventId': {
      id: '/admin/arrangementer/$eventId'
      path: '/arrangementer/$eventId'
      fullPath: '/admin/arrangementer/$eventId'
      preLoaderRoute: typeof AdminArrangementerEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/arrangementer/ny': {
      id: '/admin/arrangementer/ny'
      path: '/arrangementer/ny'
      fullPath: '/admin/arrangementer/ny'
      preLoaderRoute: typeof AdminArrangementerNyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/profil/$id/': {
      id: '/_app/profil/$id/'
      path: '/'
      fullPath: '/profil/$id/'
      preLoaderRoute: typeof AppProfilIdIndexRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/arrangementer': {
      id: '/_app/profil/$id/arrangementer'
      path: '/arrangementer'
      fullPath: '/profil/$id/arrangementer'
      preLoaderRoute: typeof AppProfilIdArrangementerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/innstillinger': {
      id: '/_app/profil/$id/innstillinger'
      path: '/innstillinger'
      fullPath: '/profil/$id/innstillinger'
      preLoaderRoute: typeof AppProfilIdInnstillingerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/medlemskap': {
      id: '/_app/profil/$id/medlemskap'
      path: '/medlemskap'
      fullPath: '/profil/$id/medlemskap'
      preLoaderRoute: typeof AppProfilIdMedlemskapRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/prikker': {
      id: '/_app/profil/$id/prikker'
      path: '/prikker'
      fullPath: '/profil/$id/prikker'
      preLoaderRoute: typeof AppProfilIdPrikkerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/profil/$id/sporreskjemaer': {
      id: '/_app/profil/$id/sporreskjemaer'
      path: '/sporreskjemaer'
      fullPath: '/profil/$id/sporreskjemaer'
      preLoaderRoute: typeof AppProfilIdSporreskjemaerRouteImport
      parentRoute: typeof AppProfilIdRoute
    }
    '/_app/sporreskjema/$id_/svar': {
      id: '/_app/sporreskjema/$id_/svar'
      path: '/sporreskjema/$id/svar'
      fullPath: '/sporreskjema/$id/svar'
      preLoaderRoute: typeof AppSporreskjemaIdSvarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProfilIdRouteChildren {
  AppProfilIdArrangementerRoute: typeof AppProfilIdArrangementerRoute
  AppProfilIdInnstillingerRoute: typeof AppProfilIdInnstillingerRoute
  AppProfilIdMedlemskapRoute: typeof AppProfilIdMedlemskapRoute
  AppProfilIdPrikkerRoute: typeof AppProfilIdPrikkerRoute
  AppProfilIdSporreskjemaerRoute: typeof AppProfilIdSporreskjemaerRoute
  AppProfilIdIndexRoute: typeof AppProfilIdIndexRoute
}

const AppProfilIdRouteChildren: AppProfilIdRouteChildren = {
  AppProfilIdArrangementerRoute: AppProfilIdArrangementerRoute,
  AppProfilIdInnstillingerRoute: AppProfilIdInnstillingerRoute,
  AppProfilIdMedlemskapRoute: AppProfilIdMedlemskapRoute,
  AppProfilIdPrikkerRoute: AppProfilIdPrikkerRoute,
  AppProfilIdSporreskjemaerRoute: AppProfilIdSporreskjemaerRoute,
  AppProfilIdIndexRoute: AppProfilIdIndexRoute,
}

const AppProfilIdRouteWithChildren = AppProfilIdRoute._addFileChildren(
  AppProfilIdRouteChildren,
)

interface AppRouteChildren {
  AppKokebokRoute: typeof AppKokebokRoute
  AppKontraktRoute: typeof AppKontraktRoute
  AppNyStudentRoute: typeof AppNyStudentRoute
  AppOpptakRoute: typeof AppOpptakRoute
  AppPersonvernRoute: typeof AppPersonvernRoute
  AppQrKoderRoute: typeof AppQrKoderRoute
  AppSoknaderRoute: typeof AppSoknaderRoute
  AppToddelRoute: typeof AppToddelRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnnonserSlugRoute: typeof AppAnnonserSlugRoute
  AppArrangementerSlugRoute: typeof AppArrangementerSlugRoute
  AppBedriftStudieneRoute: typeof AppBedriftStudieneRoute
  AppGalleriSlugRoute: typeof AppGalleriSlugRoute
  AppGrupperSlugRoute: typeof AppGrupperSlugRoute
  AppMotetidSlugRoute: typeof AppMotetidSlugRoute
  AppMotetidNyRoute: typeof AppMotetidNyRoute
  AppNyheterSlugRoute: typeof AppNyheterSlugRoute
  AppPlaygroundMarkdownRoute: typeof AppPlaygroundMarkdownRoute
  AppProfilIdRoute: typeof AppProfilIdRouteWithChildren
  AppSporreskjemaIdRoute: typeof AppSporreskjemaIdRoute
  AppAnnonserIndexRoute: typeof AppAnnonserIndexRoute
  AppArrangementerIndexRoute: typeof AppArrangementerIndexRoute
  AppBedriftIndexRoute: typeof AppBedriftIndexRoute
  AppGalleriIndexRoute: typeof AppGalleriIndexRoute
  AppGrupperIndexRoute: typeof AppGrupperIndexRoute
  AppMotetidIndexRoute: typeof AppMotetidIndexRoute
  AppNyheterIndexRoute: typeof AppNyheterIndexRoute
  AppSporreskjemaIdSvarRoute: typeof AppSporreskjemaIdSvarRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKokebokRoute: AppKokebokRoute,
  AppKontraktRoute: AppKontraktRoute,
  AppNyStudentRoute: AppNyStudentRoute,
  AppOpptakRoute: AppOpptakRoute,
  AppPersonvernRoute: AppPersonvernRoute,
  AppQrKoderRoute: AppQrKoderRoute,
  AppSoknaderRoute: AppSoknaderRoute,
  AppToddelRoute: AppToddelRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnnonserSlugRoute: AppAnnonserSlugRoute,
  AppArrangementerSlugRoute: AppArrangementerSlugRoute,
  AppBedriftStudieneRoute: AppBedriftStudieneRoute,
  AppGalleriSlugRoute: AppGalleriSlugRoute,
  AppGrupperSlugRoute: AppGrupperSlugRoute,
  AppMotetidSlugRoute: AppMotetidSlugRoute,
  AppMotetidNyRoute: AppMotetidNyRoute,
  AppNyheterSlugRoute: AppNyheterSlugRoute,
  AppPlaygroundMarkdownRoute: AppPlaygroundMarkdownRoute,
  AppProfilIdRoute: AppProfilIdRouteWithChildren,
  AppSporreskjemaIdRoute: AppSporreskjemaIdRoute,
  AppAnnonserIndexRoute: AppAnnonserIndexRoute,
  AppArrangementerIndexRoute: AppArrangementerIndexRoute,
  AppBedriftIndexRoute: AppBedriftIndexRoute,
  AppGalleriIndexRoute: AppGalleriIndexRoute,
  AppGrupperIndexRoute: AppGrupperIndexRoute,
  AppMotetidIndexRoute: AppMotetidIndexRoute,
  AppNyheterIndexRoute: AppNyheterIndexRoute,
  AppSporreskjemaIdSvarRoute: AppSporreskjemaIdSvarRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthKobleFeideRoute: typeof AuthKobleFeideRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVelgPassordRoute: typeof AuthVelgPassordRoute
  AuthOauthConsentRoute: typeof AuthOauthConsentRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthKobleFeideRoute: AuthKobleFeideRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVelgPassordRoute: AuthVelgPassordRoute,
  AuthOauthConsentRoute: AuthOauthConsentRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DevRouteChildren {
  DevFormTestRoute: typeof DevFormTestRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevFormTestRoute: DevFormTestRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface AdminSuperAdminRouteChildren {
  AdminSuperAdminApiKeysRoute: typeof AdminSuperAdminApiKeysRoute
  AdminSuperAdminDatabaseRoute: typeof AdminSuperAdminDatabaseRoute
  AdminSuperAdminLogsRoute: typeof AdminSuperAdminLogsRoute
  AdminSuperAdminOauthClientsRoute: typeof AdminSuperAdminOauthClientsRoute
}

const AdminSuperAdminRouteChildren: AdminSuperAdminRouteChildren = {
  AdminSuperAdminApiKeysRoute: AdminSuperAdminApiKeysRoute,
  AdminSuperAdminDatabaseRoute: AdminSuperAdminDatabaseRoute,
  AdminSuperAdminLogsRoute: AdminSuperAdminLogsRoute,
  AdminSuperAdminOauthClientsRoute: AdminSuperAdminOauthClientsRoute,
}

const AdminSuperAdminRouteWithChildren = AdminSuperAdminRoute._addFileChildren(
  AdminSuperAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminSuperAdminRoute: typeof AdminSuperAdminRouteWithChildren
  AdminAnnonserRoute: typeof AdminAnnonserRoute
  AdminBannereRoute: typeof AdminBannereRoute
  AdminBrukereRoute: typeof AdminBrukereRoute
  AdminGalleriRoute: typeof AdminGalleriRoute
  AdminGrupperRoute: typeof AdminGrupperRoute
  AdminKontaktskjemaRoute: typeof AdminKontaktskjemaRoute
  AdminNyheterRoute: typeof AdminNyheterRoute
  AdminOpptakRoute: typeof AdminOpptakRoute
  AdminPrikkerRoute: typeof AdminPrikkerRoute
  AdminRollerRoute: typeof AdminRollerRoute
  AdminSoknaderRoute: typeof AdminSoknaderRoute
  AdminToddelRoute: typeof AdminToddelRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArrangementerEventIdRoute: typeof AdminArrangementerEventIdRoute
  AdminArrangementerNyRoute: typeof AdminArrangementerNyRoute
  AdminArrangementerIndexRoute: typeof AdminArrangementerIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSuperAdminRoute: AdminSuperAdminRouteWithChildren,
  AdminAnnonserRoute: AdminAnnonserRoute,
  AdminBannereRoute: AdminBannereRoute,
  AdminBrukereRoute: AdminBrukereRoute,
  AdminGalleriRoute: AdminGalleriRoute,
  AdminGrupperRoute: AdminGrupperRoute,
  AdminKontaktskjemaRoute: AdminKontaktskjemaRoute,
  AdminNyheterRoute: AdminNyheterRoute,
  AdminOpptakRoute: AdminOpptakRoute,
  AdminPrikkerRoute: AdminPrikkerRoute,
  AdminRollerRoute: AdminRollerRoute,
  AdminSoknaderRoute: AdminSoknaderRoute,
  AdminToddelRoute: AdminToddelRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArrangementerEventIdRoute: AdminArrangementerEventIdRoute,
  AdminArrangementerNyRoute: AdminArrangementerNyRoute,
  AdminArrangementerIndexRoute: AdminArrangementerIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
