ALTER TABLE "org_group_position" ADD COLUMN "global_permissions" text[] DEFAULT '{}' NOT NULL;--> statement-breakpoint
UPDATE "org_group" SET
  "leader_global_permissions" = array(select distinct p from unnest(leader_global_permissions || array(select p from unnest(leader_permissions) p where p ~ '^(news|jobs|banners|toddel|galleries|users):')) p),
  "leader_permissions" = array(select p from unnest(leader_permissions) p where p = any(ARRAY['events:create', 'events:update', 'events:delete', 'events:manage', 'events:registrations:view', 'events:registrations:create', 'events:payments:view', 'events:payments:refund', 'roles:view', 'roles:create', 'roles:update', 'roles:delete', 'roles:assign', 'forms:view', 'forms:create', 'forms:update', 'forms:delete', 'forms:manage', 'applications:expense:view', 'applications:expense:manage', 'applications:support:view', 'applications:support:manage', 'groups:view', 'groups:update', 'groups:manage', 'contracts:view', 'contracts:manage']::text[]))
WHERE exists (select 1 from unnest(leader_permissions) p where not (p = any(ARRAY['events:create', 'events:update', 'events:delete', 'events:manage', 'events:registrations:view', 'events:registrations:create', 'events:payments:view', 'events:payments:refund', 'roles:view', 'roles:create', 'roles:update', 'roles:delete', 'roles:assign', 'forms:view', 'forms:create', 'forms:update', 'forms:delete', 'forms:manage', 'applications:expense:view', 'applications:expense:manage', 'applications:support:view', 'applications:support:manage', 'groups:view', 'groups:update', 'groups:manage', 'contracts:view', 'contracts:manage']::text[])));--> statement-breakpoint
UPDATE "org_group" SET
  "member_global_permissions" = array(select distinct p from unnest(member_global_permissions || array(select p from unnest(member_permissions) p where p ~ '^(news|jobs|banners|toddel|galleries|users):')) p),
  "member_permissions" = array(select p from unnest(member_permissions) p where p = any(ARRAY['events:create', 'events:update', 'events:delete', 'events:manage', 'events:registrations:view', 'events:registrations:create', 'events:payments:view', 'events:payments:refund', 'roles:view', 'roles:create', 'roles:update', 'roles:delete', 'roles:assign', 'forms:view', 'forms:create', 'forms:update', 'forms:delete', 'forms:manage', 'applications:expense:view', 'applications:expense:manage', 'applications:support:view', 'applications:support:manage', 'groups:view', 'groups:update', 'groups:manage', 'contracts:view', 'contracts:manage']::text[]))
WHERE exists (select 1 from unnest(member_permissions) p where not (p = any(ARRAY['events:create', 'events:update', 'events:delete', 'events:manage', 'events:registrations:view', 'events:registrations:create', 'events:payments:view', 'events:payments:refund', 'roles:view', 'roles:create', 'roles:update', 'roles:delete', 'roles:assign', 'forms:view', 'forms:create', 'forms:update', 'forms:delete', 'forms:manage', 'applications:expense:view', 'applications:expense:manage', 'applications:support:view', 'applications:support:manage', 'groups:view', 'groups:update', 'groups:manage', 'contracts:view', 'contracts:manage']::text[])));--> statement-breakpoint
UPDATE "org_group_position" SET
  "global_permissions" = array(select distinct p from unnest(global_permissions || array(select p from unnest(permissions) p where p ~ '^(news|jobs|banners|toddel|galleries|users):')) p),
  "permissions" = array(select p from unnest(permissions) p where p = any(ARRAY['events:create', 'events:update', 'events:delete', 'events:manage', 'events:registrations:view', 'events:registrations:create', 'events:payments:view', 'events:payments:refund', 'roles:view', 'roles:create', 'roles:update', 'roles:delete', 'roles:assign', 'forms:view', 'forms:create', 'forms:update', 'forms:delete', 'forms:manage', 'applications:expense:view', 'applications:expense:manage', 'applications:support:view', 'applications:support:manage', 'groups:view', 'groups:update', 'groups:manage', 'contracts:view', 'contracts:manage']::text[]))
WHERE "scope" = 'group' AND exists (select 1 from unnest(permissions) p where not (p = any(ARRAY['events:create', 'events:update', 'events:delete', 'events:manage', 'events:registrations:view', 'events:registrations:create', 'events:payments:view', 'events:payments:refund', 'roles:view', 'roles:create', 'roles:update', 'roles:delete', 'roles:assign', 'forms:view', 'forms:create', 'forms:update', 'forms:delete', 'forms:manage', 'applications:expense:view', 'applications:expense:manage', 'applications:support:view', 'applications:support:manage', 'groups:view', 'groups:update', 'groups:manage', 'contracts:view', 'contracts:manage']::text[])));
