import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import openapiTS, { COMMENT_HEADER, astToString } from "openapi-typescript";
import { createApp } from "../../../apps/api/src/app";
import type { AppContext, AppServices } from "../../../apps/api/src/lib/ctx";

const GENERATED_HEADER = "// This file is auto-generated by `bun run codegen`.\n// Do not edit this file directly.\n\n";

function toTypeName(name: string): string {
  const words = name
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  const pascal = words
    .map((word) => {
      const first = word.charAt(0).toUpperCase();
      return `${first}${word.slice(1)}`;
    })
    .join("");

  const base = pascal || "Schema";
  return /^[0-9]/.test(base) ? `Schema${base}` : base;
}

const app = await createApp({
  ctx: {} as AppContext,
  service: {} as AppServices,
});

const response = await app.request("/openapi");
if (!response.ok) {
  const body = await response.text();
  throw new Error(`Failed to fetch OpenAPI spec: ${response.status}\n${body}`);
}

const openapiSpec = await response.json();
const ast = await openapiTS(openapiSpec);
const generatedTypes = `${COMMENT_HEADER}${astToString(ast)}`;

const generatedDir = resolve(import.meta.dir, "../src/generated");
const outputPath = resolve(generatedDir, "openapi.ts");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generatedTypes);

const schemaKeys = Object.keys((openapiSpec as { components?: { schemas?: Record<string, unknown> } }).components?.schemas ?? {}).sort((a, b) =>
  a.localeCompare(b),
);

const usedNames = new Set<string>();
const schemaAliases = schemaKeys.map((schemaKey) => {
  const rawName = toTypeName(schemaKey);
  let alias = rawName;
  let counter = 2;
  while (usedNames.has(alias)) {
    alias = `${rawName}${counter}`;
    counter++;
  }
  usedNames.add(alias);
  return { alias, schemaKey };
});

const schemasFile = `${GENERATED_HEADER}import type { components } from "./openapi";

export type Schemas = components["schemas"];
export type SchemaNames = keyof Schemas;
export type SchemaOf<TName extends SchemaNames> = Schemas[TName];
${schemaAliases.map(({ alias, schemaKey }) => `\nexport type ${alias} = Schemas[${JSON.stringify(schemaKey)}];`).join("")}
`;
await writeFile(resolve(generatedDir, "schemas.ts"), schemasFile);

const generatedIndexFile = `${GENERATED_HEADER}export type * from "./openapi";
export type * from "./schemas";
`;
await writeFile(resolve(generatedDir, "index.ts"), generatedIndexFile);

console.log(`OpenAPI types generated at ${outputPath} with ${schemaAliases.length} schema aliases`);
