name: Deploy to Drift

on:
  push:
    branches:
      - main
  # workflow_run:
  #   workflows: ["Check Code Quality"]
  #   types:
  #     - completed
  #   branches:
  #     - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    concurrency:
      group: deployment_lock
      cancel-in-progress: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH key
        env:
          PROXY_HOST: ${{ vars.PROXY_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          ssh-keyscan -H $PROXY_HOST >> ~/.ssh/known_hosts

      - name: Deploy to OpenStack server
        env:
          PROXY_HOST: ${{ vars.PROXY_HOST }}
          HOST: ${{ vars.HOST }}
          USER: ${{ vars.USER }}
          WORKING_DIR: ${{ vars.WORKING_DIR }}
          VAULTWARDEN_ITEM_ID: ${{ vars.VAULTWARDEN_ITEM_ID }}
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/key
          ssh -J $USER@$PROXY_HOST $USER@$HOST << ENDSSH
          set -euo pipefail
          sudo -i
          ./get-env.sh $VAULTWARDEN_ITEM_ID $WORKING_DIR/.env
          cd $WORKING_DIR
          git fetch
          git reset --hard origin/main
          chmod 0600 .env
          pnpm prod:up
          ENDSSH
